// LIC// ====================================================================
// LIC// This file forms part of oomph-lib, the object-oriented,
// LIC// multi-physics finite-element library, available
// LIC// at http://www.oomph-lib.org.
// LIC//
// LIC// Copyright (C) 2006-2022 Matthias Heil and Andrew Hazel
// LIC//
// LIC// This library is free software; you can redistribute it and/or
// LIC// modify it under the terms of the GNU Lesser General Public
// LIC// License as published by the Free Software Foundation; either
// LIC// version 2.1 of the License, or (at your option) any later version.
// LIC//
// LIC// This library is distributed in the hope that it will be useful,
// LIC// but WITHOUT ANY WARRANTY; without even the implied warranty of
// LIC// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// LIC// Lesser General Public License for more details.
// LIC//
// LIC// You should have received a copy of the GNU Lesser General Public
// LIC// License along with this library; if not, write to the Free Software
// LIC// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
// LIC// 02110-1301  USA.
// LIC//
// LIC// The authors may be contacted at oomph-lib@maths.man.ac.uk.
// LIC//
// LIC//====================================================================
// Include guard to prevent multiple inclusions of the header
#ifndef OOMPH_AXISYM_NAVIER_STOKES_FLUX_CONTROL_ELEMENTS
#define OOMPH_AXISYM_NAVIER_STOKES_FLUX_CONTROL_ELEMENTS

// Config header generated by autoconfig
#ifdef HAVE_CONFIG_H
#include <oomph-lib-config.h>
#endif

// OOMPH-LIB headers
#include "../generic/nodes.h"
#include "../navier_stokes/navier_stokes_surface_power_elements.h"
#include "../navier_stokes/navier_stokes_flux_control_elements.h"
#include "axisym_navier_stokes_surface_power_elements.h"

namespace oomph
{
  //======================================================================
  /// A class of element to impose an applied boundary pressure to
  /// Navier-Stokes elements to control to control a volume flux. A mesh of
  /// these elements are used in conjunction with a NetFluxControlElement.
  /// The template arguement ELEMENT is a Navier-Stokes "bulk" element.
  ///
  /// Note: This element calculates Jacobian contributions for both itself
  /// and also for the NetFluxControlElement with respect to its unknowns.
  //======================================================================
  template<class ELEMENT>
  class AxisymmetricNavierStokesFluxControlElement
    : public virtual TemplateFreeNavierStokesFluxControlElementBase,
      public virtual AxisymmetricNavierStokesSurfacePowerElement<ELEMENT>
  {
  public:
    /// Constructor, which takes a "bulk" element and face index
    AxisymmetricNavierStokesFluxControlElement(
      FiniteElement* const& element_pt,
      const int& face_index,
      const bool& called_from_refineable_constructor = false)
      : AxisymmetricNavierStokesSurfacePowerElement<ELEMENT>(element_pt,
                                                             face_index)
    {
#ifdef PARANOID
      {
        // Check that the element is not a refineable 3d element
        if (!called_from_refineable_constructor)
        {
          ELEMENT* elem_pt = new ELEMENT;
          // If it's three-d
          if (elem_pt->dim() == 3)
          {
            // Is it refineable
            if (dynamic_cast<RefineableElement*>(elem_pt))
            {
              // Throw Error
              std::ostringstream error_message;
              error_message
                << "This element does not work properly with refineable bulk \n"
                << "elements in 3D. Please use the refineable version\n"
                << "instead.\n";
              throw OomphLibError(error_message.str(),
                                  OOMPH_CURRENT_FUNCTION,
                                  OOMPH_EXCEPTION_LOCATION);
            }
          }
        }
      }
#endif

      // Set the dimension from the dimension of the first node (since Dim is
      // private in the parent class)
      Dim = this->node_pt(0)->ndim();

      // Get the indices at which the velocity components are stored
      U_nodal_index.resize(this->Dim);
      for (unsigned i = 0; i < this->Dim; i++)
      {
        U_nodal_index[i] =
          dynamic_cast<ELEMENT*>(this->bulk_element_pt())->u_index_nst(i);
      }
    }

    /// Destructor should not delete anything
    ~AxisymmetricNavierStokesFluxControlElement() {}

    /// This function returns just the residuals
    inline void fill_in_contribution_to_residuals(Vector<double>& residuals)
    {
      // Call the generic residuals function using a dummy matrix argument
      fill_in_contribution_to_residuals_axisymmetric_nst_traction(
        residuals, GeneralisedElement::Dummy_matrix, 0);
    }

    /// This function returns the residuals and the Jacobian
    /// including the Jacobian contribution from the flux control
    /// master element with respect to dof in this
    /// element
    inline void fill_in_contribution_to_jacobian(Vector<double>& residuals,
                                                 DenseMatrix<double>& jacobian)
    {
      // Call the generic routine
      FiniteElement::fill_in_contribution_to_jacobian(residuals, jacobian);

      // fill_in_contribution_to_residuals_axisymmetric_nst_traction(
      //  residuals, jacobian, 1);
    }

    /// Function to get the integral of the volume flux
    double get_volume_flux()
    {
      return AxisymmetricNavierStokesSurfacePowerElement<
        ELEMENT>::get_volume_flux();
    }

  protected:
    /// Access function that returns the local equation numbers
    /// for velocity components.
    /// u_local_eqn(n,i) = local equation number or < 0 if pinned.
    /// The default is to asssume that n is the local node number
    /// and the i-th velocity component is the i-th unknown stored at the node.
    virtual inline int u_local_eqn(const unsigned& n, const unsigned& i)
    {
      return this->nodal_local_eqn(n, i);
    }

    /// Function to compute the shape and test functions and to return
    /// the Jacobian of mapping
    inline double shape_and_test_at_knot(const unsigned& ipt,
                                         Shape& psi,
                                         Shape& test) const
    {
      // Find number of nodes
      unsigned n_node = this->nnode();
      // Calculate the shape functions
      this->shape_at_knot(ipt, psi);
      // Set the test functions to be the same as the shape functions
      for (unsigned i = 0; i < n_node; i++)
      {
        test[i] = psi[i];
      }
      // Return the value of the jacobian
      return this->J_eulerian_at_knot(ipt);
    }


    /// This function returns the residuals for the traction function
    /// flag=1(or 0): do (or don't) compute the Jacobian as well.
    /// This function also calculates the Jacobian contribution for the
    /// NetFluxControlElement
    void fill_in_contribution_to_residuals_axisymmetric_nst_traction(
      Vector<double>& residuals, DenseMatrix<double>& jacobian, unsigned flag)
    {
      // Find out how many nodes there are
      unsigned n_node = this->nnode();

      // Get continuous time from timestepper of first node
      double time = this->node_pt(0)->time_stepper_pt()->time_pt()->time();

#ifdef PARANOID
      // Find out how many positional dofs there are
      unsigned n_position_type = this->nnodal_position_type();
      if (n_position_type != 1)
      {
        throw OomphLibError(
          "AxisymmetricNavierStokes is not yet implemented for "
          "more than one position type",
          OOMPH_CURRENT_FUNCTION,
          OOMPH_EXCEPTION_LOCATION);
      }
#endif

      // Find out the dimension of the node
      unsigned n_dim = this->nodal_dimension();

      // Integer to hold the local equation number
      int local_eqn = 0;

      // Get the pressure at the outflow
      double pressure = this->external_data_pt(pressure_data_id())->value(0);

      // Set up memory for the shape functions
      // Note that in this case, the number of lagrangian coordinates is always
      // equal to the dimension of the nodes
      Shape psi(n_node);
      DShape dpsids(n_node, n_dim - 1);

      // Set the value of n_intpt
      unsigned n_intpt = this->integral_pt()->nweight();

      // Loop over the integration points
      for (unsigned ipt = 0; ipt < n_intpt; ipt++)
      {
        // Get the integral weight
        double w = this->integral_pt()->weight(ipt);

        // Only need to call the local derivatives
        this->dshape_local_at_knot(ipt, psi, dpsids);

        // Calculate the Eulerian and Lagrangian coordinates
        Vector<double> local_x(n_dim, 0.0);

        // Also calculate the surface Vectors (derivatives wrt local
        // coordinates)
        DenseMatrix<double> interpolated_A(n_dim - 1, n_dim, 0.0);

        // Calculate positions and derivatives
        for (unsigned l = 0; l < n_node; l++)
        {
          // Loop over directions
          for (unsigned i = 0; i < n_dim; i++)
          {
            // Calculate the Eulerian coords
            local_x[i] += this->nodal_position(l, i) * psi(l);

            // Loop over LOCAL derivative directions, to calculate the
            // tangent(s)
            for (unsigned j = 0; j < n_dim - 1; j++)
            {
              interpolated_A(j, i) += this->nodal_position(l, i) * dpsids(l, j);
            }
          }
        }

        // Now find the local metric tensor from the tangent Vectors
        DenseMatrix<double> A(n_dim - 1);
        for (unsigned i = 0; i < n_dim - 1; i++)
        {
          for (unsigned j = 0; j < n_dim - 1; j++)
          {
            // Initialise surface metric tensor to zero
            A(i, j) = 0.0;

            // Take the dot product
            for (unsigned k = 0; k < n_dim; k++)
            {
              A(i, j) += interpolated_A(i, k) * interpolated_A(j, k);
            }
          }
        }

        // Get the outer unit normal
        Vector<double> interpolated_normal(n_dim);
        this->outer_unit_normal(ipt, interpolated_normal);

        // Find the determinant of the metric tensor
        double Adet = 0.0;
        switch (n_dim)
        {
          case 2:
            Adet = A(0, 0);
            break;
          case 3:
            Adet = A(0, 0) * A(1, 1) - A(0, 1) * A(1, 0);
            break;
          default:
            throw OomphLibError(
              "Wrong dimension in AxisymmetricNavierStokesTractionElement",
              "AxisymmetricNavierStokesTractionElement::fill_in_contribution_"
              "to_"
              "residuals()",
              OOMPH_EXCEPTION_LOCATION);
        }

        // Premultiply the weights and the square-root of the determinant of
        // the metric tensor
        double W = w * sqrt(Adet);

        // Now calculate the load
        Vector<double> traction(n_dim + 1);
        for (unsigned i = 0; i < Dim; i++)
        {
          traction[i] = -pressure * interpolated_normal[i];
        }

        // Loop over the test functions, nodes of the element
        for (unsigned l = 0; l < n_node; l++)
        {
          // Loop over the velocity components
          for (unsigned i = 0; i < n_dim + 1; i++)
          {
            // Equation number
            local_eqn = this->nodal_local_eqn(l, U_nodal_index[i]);
            /*IF it's not a boundary condition*/
            if (local_eqn >= 0)
            {
              // Add the loading terms to the residuals
              residuals[local_eqn] -= traction[i] * psi(l) * local_x[0] * W;
            }
          }
        } // End of loop over shape functions
      } // End of loop over integration points
    }

    /// This function returns the residuals for the traction function
    /// flag=1(or 0): do (or don't) compute the Jacobian as well.
    /// This function also calculates the Jacobian contribution for the
    /// NetFluxControlElement
    void fill_in_generic_residual_contribution_fluid_traction(
      Vector<double>& residuals, DenseMatrix<double>& jacobian, unsigned flag)
    {
      // Find out how many nodes there are
      unsigned n_node = this->nnode();

      // Set up memory for the shape and test functions
      Shape psif(n_node), testf(n_node);

      // Set the value of n_intpt
      unsigned n_intpt = this->integral_pt()->nweight();

      // Integers to store local equation numbers
      int local_eqn = 0;

      // Get the pressure at the outflow
      double pressure = this->external_data_pt(pressure_data_id())->value(0);

      // Loop over the integration points
      for (unsigned ipt = 0; ipt < n_intpt; ipt++)
      {
        // Get the integral weight
        double w = this->integral_pt()->weight(ipt);

        // Find the shape and test functions and return the Jacobian
        // of the mapping
        double J = shape_and_test_at_knot(ipt, psif, testf);

        // Premultiply the weights and the Jacobian
        double W = w * J;

        // Get the outer unit normal
        Vector<double> unit_normal(Dim);
        this->outer_unit_normal(ipt, unit_normal);

        // Calculate the traction
        Vector<double> traction(Dim);
        for (unsigned i = 0; i < Dim; i++)
        {
          traction[i] = -pressure * unit_normal[i];
        }

        // Loop over the test functions
        for (unsigned l = 0; l < n_node; l++)
        {
          // Loop over the velocity components
          for (unsigned i = 0; i < Dim; i++)
          {
            local_eqn = u_local_eqn(l, i);

            /*IF it's not a boundary condition*/
            if (local_eqn >= 0)
            {
              // Add the user-defined traction terms
              residuals[local_eqn] += traction[i] * testf[l] * W;

              // Calculate the Jacobian if required. It is assumed
              // that traction DOES NOT depend upon velocities
              // or pressures in the Navier Stokes elements, but
              // depend in the Data value which holds the
              // pressure.
              if (flag)
              {
                // Get equation number of the pressure data unknown
                int local_unknown =
                  this->external_local_eqn(pressure_data_id(), 0);

                // IF it's not a boundary condition
                if (local_unknown >= 0)
                {
                  // Add to Jacobian for this element
                  double jac_contribution = -unit_normal[i] * testf[l] * W;
                  jacobian(local_eqn, local_unknown) += jac_contribution;

                  // Add to Jacobian for master element
                  jacobian(local_unknown, local_eqn) += jac_contribution;
                }
              }
            }
          } // End of loop over dimension
        } // End of loop over shape functions
      }
    }

  protected:
    /// The highest dimension of the problem
    unsigned Dim;

    /// The nodal indices of the velocity
    Vector<unsigned> U_nodal_index;
  };


  /// //////////////////////////////////////////////////////////////////////
  /// //////////////////////////////////////////////////////////////////////
  /// //////////////////////////////////////////////////////////////////////


  //======================================================================
  /// A class of element to impose an applied boundary pressure to
  /// Navier-Stokes elements to control to control a volume flux. A mesh of
  /// these elements are used in conjunction with a NetFluxControlElement.
  /// The template arguement ELEMENT is a Navier-Stokes "bulk" element.
  ///
  /// Note: This element calculates Jacobian contributions for both itself
  /// and also for the NetFluxControlElement with respect to its unknowns.
  ///
  /// THIS IS THE REFINEABLE VERSION.
  //======================================================================
  template<class ELEMENT>
  class RefineableAxisymmetricNavierStokesFluxControlElement
    : public virtual AxisymmetricNavierStokesFluxControlElement<ELEMENT>,
      public virtual NonRefineableElementWithHangingNodes
  {
  public:
    /// Constructor, which takes a "bulk" element and the face index
    RefineableAxisymmetricNavierStokesFluxControlElement(
      FiniteElement* const& element_pt, const int& face_index)
      : AxisymmetricNavierStokesSurfacePowerElement<ELEMENT>(element_pt,
                                                             face_index),
        // we're calling this from the constructor of the refineable
        // version.
        AxisymmetricNavierStokesFluxControlElement<ELEMENT>(
          element_pt, face_index, true)
    {
    }

    /// Destructor should not delete anything
    ~RefineableAxisymmetricNavierStokesFluxControlElement() {}


    /// Number of continuously interpolated values are the
    /// same as those in the bulk element.
    unsigned ncont_interpolated_values() const
    {
      return dynamic_cast<ELEMENT*>(this->bulk_element_pt())
        ->ncont_interpolated_values();
    }

    /// This function returns just the residuals
    inline void fill_in_contribution_to_residuals(Vector<double>& residuals)
    {
      // Call the generic residuals function using a dummy matrix argument
      refineable_fill_in_generic_residual_contribution_fluid_traction(
        residuals, GeneralisedElement::Dummy_matrix, 0);
    }

    /// This function returns the residuals and the Jacobian
    /// including the Jacobian contribution from the flux control
    /// master element with respect to dof in this
    /// element
    inline void fill_in_contribution_to_jacobian(Vector<double>& residuals,
                                                 DenseMatrix<double>& jacobian)
    {
      // Call the generic routine
      refineable_fill_in_generic_residual_contribution_fluid_traction(
        residuals, jacobian, 1);
    }

  protected:
    /// This function returns the residuals for the traction function
    /// flag=1(or 0): do (or don't) compute the Jacobian as well.
    /// This function also calculates the Jacobian contribution for the
    /// NetFluxControlElement
    void refineable_fill_in_generic_residual_contribution_fluid_traction(
      Vector<double>& residuals, DenseMatrix<double>& jacobian, unsigned flag)
    {
      // Get the indices at which the velocity components are stored
      unsigned u_nodal_index[this->Dim];
      for (unsigned i = 0; i < this->Dim; i++)
      {
        u_nodal_index[i] =
          dynamic_cast<ELEMENT*>(this->bulk_element_pt())->u_index_nst(i);
      }

      // Pointer to hang info object
      HangInfo* hang_info_pt = 0;

      // Find out how many nodes there are
      unsigned n_node = this->nnode();

      // Set up memory for the shape and test functions
      Shape psif(n_node), testf(n_node);

      // Set the value of n_intpt
      unsigned n_intpt = this->integral_pt()->nweight();

      // Integers to store local equation numbers
      int local_eqn = 0;

      // Get the pressure at the outflow
      double pressure =
        this->external_data_pt(this->pressure_data_id())->value(0);

      // Loop over the integration points
      for (unsigned ipt = 0; ipt < n_intpt; ipt++)
      {
        // Get the integral weight
        double w = this->integral_pt()->weight(ipt);

        // Find the shape and test functions and return the Jacobian
        // of the mapping
        double J = this->shape_and_test_at_knot(ipt, psif, testf);

        // Premultiply the weights and the Jacobian
        double W = w * J;

        // Get the outer unit normal
        Vector<double> unit_normal(this->Dim);
        this->outer_unit_normal(ipt, unit_normal);

        // Calculate the traction
        Vector<double> traction(this->Dim);
        for (unsigned i = 0; i < this->Dim; i++)
        {
          traction[i] = -pressure * unit_normal[i];
        }


        // Number of master nodes and storage for the weight of the shape
        // function
        unsigned n_master = 1;
        double hang_weight = 1.0;

        // Loop over the nodes for the test functions/equations
        //----------------------------------------------------
        for (unsigned l = 0; l < n_node; l++)
        {
          // Local boolean to indicate whether the node is hanging
          bool is_node_hanging = this->node_pt(l)->is_hanging();

          // If the node is hanging
          if (is_node_hanging)
          {
            hang_info_pt = this->node_pt(l)->hanging_pt();

            // Read out number of master nodes from hanging data
            n_master = hang_info_pt->nmaster();
          }
          // Otherwise the node is its own master
          else
          {
            n_master = 1;
          }

          // Loop over the master nodes
          for (unsigned m = 0; m < n_master; m++)
          {
            // Loop over velocity components for equations
            for (unsigned i = 0; i < this->Dim; i++)
            {
              // Get the equation number
              // If the node is hanging
              if (is_node_hanging)
              {
                // Get the equation number from the master node
                local_eqn = this->local_hang_eqn(
                  hang_info_pt->master_node_pt(m), u_nodal_index[i]);
                // Get the hang weight from the master node
                hang_weight = hang_info_pt->master_weight(m);
              }
              // If the node is not hanging
              else
              {
                // Local equation number
                local_eqn = this->nodal_local_eqn(l, u_nodal_index[i]);

                // Node contributes with full weight
                hang_weight = 1.0;
              }

              // If it's not a boundary condition...
              if (local_eqn >= 0)
              {
                // Add the user-defined traction terms
                residuals[local_eqn] +=
                  traction[i] * testf[l] * W * hang_weight;

                // Calculate the Jacobian if required. It is assumed
                // that traction DOES NOT depend upon velocities
                // or pressures in the Navier Stokes elements, but
                // depend in the Data value which holds the
                // pressure.
                if (flag)
                {
                  // Get equation number of the pressure data unknown
                  int local_unknown =
                    this->external_local_eqn(this->pressure_data_id(), 0);

                  // IF it's not a boundary condition
                  if (local_unknown >= 0)
                  {
                    // Add to Jacobian for this element
                    double jac_contribution =
                      -unit_normal[i] * testf[l] * W * hang_weight;
                    jacobian(local_eqn, local_unknown) += jac_contribution;

                    // Add to Jacobian for master element
                    jacobian(local_unknown, local_eqn) += jac_contribution;
                  }
                }
              }
            } // End of loop over dimension
          } // End of loop over master nodes
        } // End of loop over nodes
      }
    }
  };


} // namespace oomph

#endif
