// LIC// ====================================================================
// LIC// This file forms part of oomph-lib, the object-oriented,
// LIC// multi-physics finite-element library, available
// LIC// at http://www.oomph-lib.org.
// LIC//
// LIC// Copyright (C) 2006-2022 Matthias Heil and Andrew Hazel
// LIC//
// LIC// This library is free software; you can redistribute it and/or
// LIC// modify it under the terms of the GNU Lesser General Public
// LIC// License as published by the Free Software Foundation; either
// LIC// version 2.1 of the License, or (at your option) any later version.
// LIC//
// LIC// This library is distributed in the hope that it will be useful,
// LIC// but WITHOUT ANY WARRANTY; without even the implied warranty of
// LIC// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// LIC// Lesser General Public License for more details.
// LIC//
// LIC// You should have received a copy of the GNU Lesser General Public
// LIC// License along with this library; if not, write to the Free Software
// LIC// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
// LIC// 02110-1301  USA.
// LIC//
// LIC// The authors may be contacted at oomph-lib@maths.man.ac.uk.
// LIC//
// LIC//====================================================================
// Header file for (one-dimensional) free surface elements
// Include guards, to prevent multiple includes
#ifndef OOMPH_INTERFACE_ELEMENTS_HEADER
#define OOMPH_INTERFACE_ELEMENTS_HEADER

// Config header generated by autoconfig
#ifdef HAVE_CONFIG_H
#include <oomph-lib-config.h>
#endif

#include "../generic/elements.h"
#include "../generic/spines.h"
#include "../generic/shape.h"
#include "../generic/hijacked_elements.h"
#include "../navier_stokes/navier_stokes_elements.h"

namespace oomph
{
  //========================================================================
  /// Base class for elements at the boundary of free surfaces or interfaces,
  /// used typically to impose contact angle boundary conditions.
  /// The elemental dimensions are one less than those of the
  /// surface elements, or two less than those of the original bulk elements.
  /// Thus in two-dimensional and axi-symmetric problems, are points,
  /// but in three-dimensional problems, they are lines.
  /// These boundaries may be in contact with a solid surface, in which case
  /// the normal to that surface must be provided.
  // Note: The class template ELEMENT is the "bulk" FluidInterfaceElement
  //=========================================================================
  template<class ELEMENT>
  class FluidInterfaceBoundingElement : public virtual FaceGeometry<ELEMENT>,
                                        public virtual FaceElement
  {
  private:
    /// Function pointer to a wall unit normal function. Returns the
    /// unit normal on the wall, at the specified Eulerian coordinate.
    typedef void (*WallUnitNormalFctPt)(const Vector<double>& x,
                                        Vector<double>& unit_normal);

    /// Function pointer to a contact angle function. Returns the
    /// contact angle between the fluid and the wall, for a given contact line
    /// velocity
    typedef double (*ContactAngleFctPt)(const Vector<double>& x,
                                        const Vector<double>& local_u);

    /// Pointer to a wall normal function that returns
    /// the wall unit normal as a function of position in global
    /// Eulerian coordinates.
    WallUnitNormalFctPt Wall_unit_normal_fct_pt;

    /// Pointer to a contact angle function that returns
    /// the contact angle as a function of the contact line velocity.
    ContactAngleFctPt Contact_angle_fct_pt;

    /// Pointer to the desired value of the capillary number
    double* Ca_pt;

    // Lagrange multipler id
    unsigned Id;

  protected:
    /// Flag used to determine whether the contact angle is to be
    /// used (0 if not), and whether it will be applied weakly as a force term
    /// in the momentum equations (1) or by hijacking the kinematic
    /// condition (2).
    Vector<unsigned> Contact_angle_flag;

    /// Flag used to determine whether the contact angle is to be
    /// set by the fixed value (0) or by the function (1) (Default).
    unsigned Contact_angle_fct_flag;

  public:
    /// Constructor
    FluidInterfaceBoundingElement(FiniteElement* const& element_pt,
                                  const int& face_index,
                                  const unsigned& id = 0)
      : Wall_unit_normal_fct_pt(0),
        Contact_angle_fct_pt(0),
        Ca_pt(0),
        Contact_angle_fct_flag(1),
        Id(id)
    {
      // Attach the geometrical information to the element. N.B. This function
      // also assigns nbulk_value from the required_nvalue of the bulk element
      element_pt->build_face_element(face_index, this);

      // we need 1 additional values for each FaceElement node, the kinematic
      // lagrange multiplier constraining the boundary motion to the wall
      Vector<unsigned> n_additional_values(nnode(), 1);

      // add storage for lagrange multipliers and set the map containing
      // the position of the first entry of this face element's
      // additional values.
      add_additional_values(n_additional_values, id);

      Contact_angle_flag = Vector<unsigned>(nnode(), 0);
    }

    virtual double nst_u(const unsigned& n, const unsigned& i) const
    {
      ELEMENT* el_pt = dynamic_cast<ELEMENT*>(this->bulk_element_pt());
      return el_pt->nst_u(this->bulk_node_number(n), i);
    }

    virtual inline unsigned nst_u_local_unknown(const unsigned& n,
                                                const unsigned& i) const
    {
      ELEMENT* el_pt = dynamic_cast<ELEMENT*>(this->bulk_element_pt());
      return el_pt->nst_u_local_unknown(this->bulk_node_number(n), i);
    }

    virtual inline unsigned nst_momentum_local_eqn(const unsigned& n,
                                                   const unsigned& i) const
    {
      ELEMENT* el_pt = dynamic_cast<ELEMENT*>(this->bulk_element_pt());
      return el_pt->nst_momentum_local_eqn(this->bulk_node_number(n), i);
    }

    /// Function that is used to determine the local equation number of
    /// the kinematic equation associated with the nodes of the element
    /// This must be overloaded depending on the node update scheme
    virtual int wall_bounded_kinematic_local_eqn(const unsigned& n)
    {
      BoundaryNodeBase* bnod_pt = dynamic_cast<BoundaryNodeBase*>(node_pt(n));
      unsigned first_index =
        bnod_pt->index_of_first_value_assigned_by_face_element(Id);
      return this->nodal_local_eqn(n, first_index);
    }

    virtual double lagrange_multiplier(const unsigned& n)
    {
      BoundaryNodeBase* bnod_pt = dynamic_cast<BoundaryNodeBase*>(node_pt(n));
      unsigned first_index =
        bnod_pt->index_of_first_value_assigned_by_face_element(Id);
      return this->nodal_value(n, first_index);
    }

    virtual int fsi_kinematic_local_eqn(const unsigned& n)
    {
      ELEMENT* el_pt = dynamic_cast<ELEMENT*>(this->bulk_element_pt());
      return el_pt->kinematic_local_eqn(this->bulk_node_number(n));
    }

    virtual int fsi_lagrange_multipler(const unsigned& n)
    {
      ELEMENT* el_pt = dynamic_cast<ELEMENT*>(this->bulk_element_pt());
      return el_pt->lagrange_multiplier(this->bulk_node_number(n));
    }

    /// Access function: Pointer to wall unit normal function
    WallUnitNormalFctPt& wall_unit_normal_fct_pt()
    {
      return Wall_unit_normal_fct_pt;
    }

    /// Access function: Pointer to wall unit normal function. Const version
    WallUnitNormalFctPt wall_unit_normal_fct_pt() const
    {
      return Wall_unit_normal_fct_pt;
    }

    // Get the contact angle from the double pointer or function pointer
    double get_contact_angle(const Vector<double>& x,
                             const Vector<double>& local_u)
    {
#ifdef PARANOID
      if (Contact_angle_fct_pt == 0)
      {
        std::ostringstream error_message;
        error_message << "The contact angle function has not been set."
                      << std::endl;
        throw OomphLibError(error_message.str(),
                            OOMPH_CURRENT_FUNCTION,
                            OOMPH_EXCEPTION_LOCATION);
      }
#endif

      return (*Contact_angle_fct_pt)(x, local_u);
    }

    void set_contact_angle_fct(const ContactAngleFctPt& contact_angle_fct_pt)
    {
      Contact_angle_fct_pt = contact_angle_fct_pt;
    }

    void set_strong_imposition(const unsigned& n)
    {
      // Hijack the bulk element residuals
      dynamic_cast<ELEMENT*>(bulk_element_pt())
        ->hijack_kinematic_conditions(this->bulk_node_number(n));

      this->fix_lagrange_multiplier(n);

      Contact_angle_flag[n] = 2;
    }

    void set_weak_imposition(const unsigned& n)
    {
      std::string error_message =
        "unhijack_kinematic_conditions not implemented.";
      throw OomphLibError(
        error_message, OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
      // Un-hijack the bulk element residuals

      // dynamic_cast<ELEMENT*>(bulk_element_pt())
      //   ->unhijack_kinematic_conditions(this->bulk_node_number(n));

      this->free_lagrange_multiplier(n);

      Contact_angle_flag[n] = 1;
    }

    void fix_lagrange_multiplier(const unsigned& n)
    {
      BoundaryNodeBase* bnod_pt = dynamic_cast<BoundaryNodeBase*>(node_pt(n));
      unsigned first_index =
        bnod_pt->index_of_first_value_assigned_by_face_element(Id);
      const double value = 0.0;
      return this->node_pt(n)->pin(first_index);
      return this->node_pt(n)->set_value(first_index, value);
    }

    void free_lagrange_multiplier(const unsigned& n)
    {
      BoundaryNodeBase* bnod_pt = dynamic_cast<BoundaryNodeBase*>(node_pt(n));
      unsigned first_index =
        bnod_pt->index_of_first_value_assigned_by_face_element(Id);
      return this->node_pt(n)->unpin(first_index);
    }

    /// Access function to the pointer specifying the capillary number
    double*& ca_pt()
    {
      return Ca_pt;
    }

    /// Return the value of the capillary number
    double ca()
    {
#ifdef PARANOID
      if (Ca_pt != 0)
      {
#endif
        return *Ca_pt;
#ifdef PARANOID
      }
      else
      {
        throw OomphLibError("Capillary number has not been set",
                            "FluidInterfaceBoundingElement::ca()",
                            OOMPH_EXCEPTION_LOCATION);
      }
#endif
    }

  protected:
    /// Function that returns the unit normal of the bounding wall
    /// directed out of the fluid
    void wall_unit_normal(const Vector<double>& x, Vector<double>& normal)
    {
#ifdef PARANOID
      if (Wall_unit_normal_fct_pt)
      {
#endif
        (*Wall_unit_normal_fct_pt)(x, normal);
#ifdef PARANOID
      }
      else
      {
        throw OomphLibError("Wall unit normal fct has not been set",
                            "FluidInterfaceBoundingElement::wall_unit_normal()",
                            OOMPH_EXCEPTION_LOCATION);
      }
#endif
    }

    /// The geometric data of the parent element is included as
    /// external data and so a (bulk) node update must take place after
    /// the variation of any of this external data
    inline void update_in_external_fd(const unsigned& i)
    {
      // Update the bulk element
      bulk_element_pt()->node_update();
    }

    /// The only external data are these geometric data so
    /// We can omit the reset function (relying on the next update
    // function to take care of the remesh)
    inline void reset_in_external_fd(const unsigned& i) {}

    /// We require a final node update in the bulk element
    /// after all finite differencing
    inline void reset_after_external_fd()
    {
      // Update the bulk element
      bulk_element_pt()->node_update();
    }

  public:
    /// Calculate the residuals
    void fill_in_contribution_to_residuals(Vector<double>& residuals)
    {
      // Add the residual contributions using a dummy matrix
      fill_in_generic_residual_contribution_interface_boundary(
        residuals, GeneralisedElement::Dummy_matrix, 0);
    }

    /// Calculate the generic residuals contribution
    virtual void fill_in_generic_residual_contribution_interface_boundary(
      Vector<double>& residuals, DenseMatrix<double>& jacobian, unsigned flag);


    /// Empty helper function to calculate the additional contributions
    /// arising from the node update strategy to the Jacobian within the
    /// integration loop. This will be overloaded by elements that require
    /// contributions to their underlying equations from boundary integrals.
    /// The shape functions, their derivatives w.r.t. to the local coordinates,
    /// the unit normal (OF THE ATTACHED SURFACE) and integral weight are passed
    /// in so that they do not have to be recalculated.
    virtual void add_additional_residual_contributions_interface_boundary(
      Vector<double>& residuals,
      DenseMatrix<double>& jacobian,
      const unsigned& flag,
      const Shape& psif,
      const DShape& dpsifds,
      const Vector<double>& interpolated_n,
      const double& W)
    {
    }

    /// Overload the output function
    void output(std::ostream& outfile)
    {
      FiniteElement::output(outfile);
    }

    /// Output function
    void output(std::ostream& outfile, const unsigned& n_plot)
    {
      FiniteElement::output(outfile, n_plot);
    }

    /// Overload the C-style output function
    void output(FILE* file_pt)
    {
      FiniteElement::output(file_pt);
    }

    /// C-style Output function
    void output(FILE* file_pt, const unsigned& n_plot)
    {
      FiniteElement::output(file_pt, n_plot);
    }
  }; // namespace oomph

  //=======================================================================
  /// Base class establishing common interfaces and functions for all
  /// Navier-Stokes-like fluid
  /// interface elements. Namely, elements that represent either a free
  /// surface or an interface between two fluids that have distinct
  /// momentum-like equation for each velocity component.
  //======================================================================
  class FluidInterfaceElement : public TemplateFreeNavierStokesEquationsBase
  {
  private:
    /// Pointer to the Capillary number
    double* Ca_pt;

    /// Pointer to the Strouhal number
    double* St_pt;

  protected:
    /// The Data that contains the external  pressure is stored
    /// as external Data for the element. Which external Data item is it?
    /// (int so it can be initialised to -1, indicating that external
    /// pressure hasn't been set).
    int External_data_number_of_external_pressure;

    /// Pointer to the Data item that stores the external pressure
    Data* Pext_data_pt;

    /// Which of the values in Pext_data_pt stores the external pressure
    unsigned Index_of_external_pressure_value;

    /// Access function that returns the local equation number
    /// for the (scalar) kinematic equation associated with the j-th local
    /// node. This must be overloaded by specific interface elements
    /// and depends on the method for handing the free-surface deformation.
    virtual int kinematic_local_eqn(const unsigned& n)
    {
      std::ostringstream error_message;
      error_message
        << "kinematic_local_eqn not implemented in base "
           "FluidInterfaceElement, use one of the inherited classes depending "
           "on how the solid displacement is implemented."
        << std::endl;
      throw OomphLibError(
        error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
    }

    /// Access function for the local equation number that
    /// corresponds to the external pressure.
    int pext_local_eqn()
    {
#ifdef PARANOID
      if (External_data_number_of_external_pressure < 0)
      {
        throw OomphLibError("No external pressure has been set\n",
                            OOMPH_CURRENT_FUNCTION,
                            OOMPH_EXCEPTION_LOCATION);
      }
#endif
      return this->external_local_eqn(External_data_number_of_external_pressure,
                                      Index_of_external_pressure_value);
    }

    /// Helper function to calculate the residuals and
    /// (if flag==1) the Jacobian of the equations.
    /// This is implemented generically using the surface
    /// divergence information that is overloaded in each element
    /// i.e. axisymmetric, two- or three-dimensional.
    virtual void fill_in_generic_residual_contribution_interface(
      Vector<double>& residuals, DenseMatrix<double>& jacobian, unsigned flag)
    {
      // Find out how many nodes there are
      unsigned n_node = this->nnode();

      // Set up memeory for the shape functions
      Shape psif(n_node);

      // Find out the number of surface coordinates
      const unsigned el_dim = this->dim();
      // We have el_dim local surface coordinates
      DShape dpsifds(n_node, el_dim);

      // Find the dimension of the problem
      // Note that this will return 2 for the axisymmetric case
      // which is correct in the sense that no
      // terms will be added in the azimuthal direction
      const unsigned n_dim = this->nodal_dimension();

      // Storage for the surface gradient
      // and divergence terms
      // These will actually be identical
      // apart from in the axisymmetric case
      DShape dpsifdS(n_node, n_dim);
      DShape dpsifdS_div(n_node, n_dim);

      // Set the value of n_intpt
      unsigned n_intpt = this->integral_pt()->nweight();

      // Get the value of the Capillary number
      double Ca = ca();

      // Get the value of the Strouhal numer
      double St = st();

      // Get the value of the external pressure
      double p_ext = pext();

      // Integers used to hold the local equation numbers and local unknowns
      int local_eqn = 0, local_unknown = 0;

      // Storage for the local coordinate
      Vector<double> s(el_dim);

      // Loop over the integration points
      for (unsigned ipt = 0; ipt < n_intpt; ipt++)
      {
        // Get the value of the local coordiantes at the integration point
        for (unsigned i = 0; i < el_dim; i++)
        {
          s[i] = this->integral_pt()->knot(ipt, i);
        }

        // Get the integral weight
        double W = this->integral_pt()->weight(ipt);

        // Call the derivatives of the shape function
        this->dshape_local_at_knot(ipt, psif, dpsifds);

        // Define and zero the tangent Vectors and local velocities
        Vector<double> interpolated_x(n_dim, 0.0);
        Vector<double> interpolated_u(n_dim, 0.0);
        Vector<double> interpolated_dx_dt(n_dim, 0.0);

        DenseMatrix<double> interpolated_t(el_dim, n_dim, 0.0);

        // Loop over the shape functions
        for (unsigned l = 0; l < n_node; l++)
        {
          const double psi_ = psif(l);
          // Loop over directional components
          for (unsigned i = 0; i < n_dim; i++)
          {
            // Coordinate
            interpolated_x[i] += this->nodal_position(l, i) * psi_;

            // Calculate velocity of mesh
            interpolated_dx_dt[i] += this->dnodal_position_dt(l, i) * psi_;

            // Calculate the tangent vectors
            for (unsigned j = 0; j < el_dim; j++)
            {
              interpolated_t(j, i) +=
                this->nodal_position(l, i) * dpsifds(l, j);
            }

            // Calculate velocity and tangent vector
            interpolated_u[i] += this->nst_u(l, i) * psi_;
          }
        }


        // Calculate the surface gradient and divergence
        double J = this->compute_surface_derivatives(
          psif, dpsifds, interpolated_t, interpolated_x, dpsifdS, dpsifdS_div);
        // Get the normal vector
        //(ALH: This could be more efficient because
        // there is some recomputation of shape functions here)
        Vector<double> interpolated_n(n_dim);
        this->outer_unit_normal(s, interpolated_n);

        // Now also get the (possible variable) surface tension
        double Sigma = this->sigma(s);

        // Loop over the shape functions
        for (unsigned l = 0; l < n_node; l++)
        {
          // Loop over the velocity components
          for (unsigned i = 0; i < n_dim; i++)
          {
            // Get the equation number for the momentum equation
            local_eqn = this->nst_momentum_local_eqn(l, i);

            // If it's not a boundary condition
            if (local_eqn >= 0)
            {
              // Add the surface-tension contribution to the momentum equation
              residuals[local_eqn] -= (Sigma / Ca) * dpsifdS_div(l, i) * J * W;

              // If the element is a free surface, add in the external pressure
              if (Pext_data_pt != 0)
              {
                // External pressure term
                residuals[local_eqn] -=
                  p_ext * interpolated_n[i] * psif(l) * J * W;

                // Add in the Jacobian term for the external pressure
                // The correct area is included in the length of the normal
                // vector
                if (flag)
                {
                  local_unknown = pext_local_eqn();
                  if (local_unknown >= 0)
                  {
                    jacobian(local_eqn, local_unknown) -=
                      interpolated_n[i] * psif(l) * J * W;
                  }
                }
              } // End of pressure contribution
            }
          } // End of contribution to momentum equation


          // Kinematic BC
          local_eqn = kinematic_local_eqn(l);
          if (local_eqn >= 0)
          {
            // Assemble the kinematic condition
            // The correct area is included in the normal vector
            for (unsigned k = 0; k < n_dim; k++)
            {
              residuals[local_eqn] +=
                (interpolated_u[k] - St * interpolated_dx_dt[k]) *
                interpolated_n[k] * psif(l) * J * W;
            }

            // Add in the jacobian
            if (flag)
            {
              // Loop over shape functions
              for (unsigned l2 = 0; l2 < n_node; l2++)
              {
                // Loop over the components
                for (unsigned i2 = 0; i2 < n_dim; i2++)
                {
                  local_unknown = this->nst_u_local_unknown(l2, i2);
                  // If it's a non-zero dof add
                  if (local_unknown >= 0)
                  {
                    jacobian(local_eqn, local_unknown) +=
                      psif(l2) * interpolated_n[i2] * psif(l) * J * W;
                  }
                }
              }
            } // End of Jacobian contribution
          }
        } // End of loop over shape functions


        // Add additional contribution required from the implementation
        // of the node update (e.g. Lagrange multpliers etc)
        add_additional_residual_contributions_interface(residuals,
                                                        jacobian,
                                                        flag,
                                                        psif,
                                                        dpsifds,
                                                        dpsifdS,
                                                        dpsifdS_div,
                                                        s,
                                                        interpolated_x,
                                                        interpolated_n,
                                                        W,
                                                        J);

      } // End of loop over integration points
    }

    /// Compute the surface gradient and surface divergence
    /// operators given the shape functions, derivatives,
    /// tangent vectors and position. All derivatives and
    /// tangent vectors should be formed
    /// with respect to the local coordinates.
    ///
    /// Return the jacobian of the surface, as well
    /// as the dpsidS, and dpsidS_div objects.
    ///
    /// This is the only
    /// function that needs to be overloaded to specify
    /// different geometries.
    ///
    /// In order to compute the surface gradient of a scalar
    /// function one needs only compute the sum over the nodes
    /// of dpsidS(l,i) * nodal_value(l,scalar_index)
    /// To compute the surface divergence of a vector quantity
    /// one computes a sum over nodes and coordinate directions
    /// dpsidS_div(l,i) * nodal_value(l,vector_index[i])
    /// In Cartesian cordinates the two surface derivatives are the
    /// same, but in Axisymmetric coordinates they are not!
    virtual double compute_surface_derivatives(
      const Shape& psi,
      const DShape& dpsids,
      const DenseMatrix<double>& interpolated_t,
      const Vector<double>& interpolated_x,
      DShape& dpsidS,
      DShape& dpsidS_div)
    {
      return 0.0;
    }

    /// Helper function to calculate the additional contributions
    /// to the resisuals and Jacobian that arise from specific node update
    /// strategies. This is called within the integration loop over the
    /// element (for efficiency) and therefore requires a fairly large
    /// number of input parameters:
    /// - the velocity shape functions and their derivatives w.r.t.
    ///   the local coordinates
    /// - the surface gradient and divergence of the velocity shape
    ///   functions
    /// - The local and Eulerian coordinates,
    /// - the outer unit normal,
    /// - the integration weight from the integration scheme
    /// - the Jacobian of the mapping between the local and global coordinates
    ///   along the element. (Note that in the axisymmmetric case this
    ///   includes the r term)!
    virtual void add_additional_residual_contributions_interface(
      Vector<double>& residuals,
      DenseMatrix<double>& jacobian,
      const unsigned& flag,
      const Shape& psif,
      const DShape& dpsifds,
      const DShape& dpsifdS,
      const DShape& dpsifdS_div,
      const Vector<double>& s,
      const Vector<double>& interpolated_x,
      const Vector<double>& interpolated_n,
      const double& W,
      const double& J)
    {
    }

  public:
    /// Constructor, set the default values of the booleans and pointers (null)
    FluidInterfaceElement() : Pext_data_pt(0)
    {
      // Initialise pointer to capillary number
      Ca_pt = 0;

      // Set the Strouhal number to the default value
      St_pt = 0;
    }

    /// Virtual function that specifies the non-dimensional
    ///  surface tension as a function of local position within the element.
    /// The default behaviour is a constant surface tension of value 1.0
    /// This function can be overloaded in more specialised elements to
    /// incorporate variations in surface tension.
    virtual double sigma(const Vector<double>& s_local)
    {
      return 1.0;
    }

    /// Calculate the residuals by calling the generic residual contribution.
    void fill_in_contribution_to_residuals(Vector<double>& residuals)
    {
      // Add the residual contributions
      fill_in_generic_residual_contribution_interface(
        residuals, GeneralisedElement::Dummy_matrix, 0);
    }

    /// The value of the Capillary number
    const double& ca() const
    {
#ifdef PARANOID
      if (Ca_pt != 0)
      {
#endif
        return *Ca_pt;
#ifdef PARANOID
      }
      else
      {
        throw OomphLibError("Capillary number has not been set",
                            "FluidInterfaceElement::ca()",
                            OOMPH_EXCEPTION_LOCATION);
      }
#endif
    }

    /// Pointer to the Capillary number
    double*& ca_pt()
    {
      return Ca_pt;
    }

    /// The value of the Strouhal number
    const double& st() const
    {
#ifdef PARANOID
      if (St_pt != 0)
      {
#endif
        return *St_pt;
#ifdef PARANOID
      }
      else
      {
        throw OomphLibError("Strouhal number has not been set",
                            "FluidInterfaceElement::st()",
                            OOMPH_EXCEPTION_LOCATION);
      }
#endif
    }

    /// The pointer to the Strouhal number
    double*& st_pt()
    {
      return St_pt;
    }

    /// Return the value of the external pressure
    double pext() const
    {
      // If the external pressure has not been set, then return a
      // default value of zero.
      if (Pext_data_pt == 0)
      {
        return 0.0;
      }
      // Otherwise return the appropriate value
      else
      {
        return Pext_data_pt->value(Index_of_external_pressure_value);
      }
    }

    /// Set the Data that contains the single pressure value
    /// that specifies the "external pressure" for the
    /// interface/free-surface. Setting this only makes sense
    /// if the interface is, in fact, a free surface (well,
    /// an interface to another inviscid fluid if you want to be picky).
    void set_external_pressure_data(Data* external_pressure_data_pt)
    {
#ifdef PARANOID
      if (external_pressure_data_pt->nvalue() != 1)
      {
        std::ostringstream error_message;
        error_message
          << "External pressure Data must only contain a single value!\n"
          << "This one contains " << external_pressure_data_pt->nvalue()
          << std::endl;

        throw OomphLibError(error_message.str(),
                            OOMPH_CURRENT_FUNCTION,
                            OOMPH_EXCEPTION_LOCATION);
      }
#endif

      // Store pointer explicitly
      Pext_data_pt = external_pressure_data_pt;

      // Add the external pressure to the element's external Data?
      // But do not finite-difference with respect to it
      this->add_external_data(Pext_data_pt, false);

      // The external pressure has just been promoted to become
      // external Data of this element -- what is its number?
      External_data_number_of_external_pressure = this->nexternal_data() - 1;

      // Index of pressure value in Data object
      Index_of_external_pressure_value = 0;
    }

    /// Set the Data that contains the pressure value
    /// that specifies the "external pressure" for the
    /// interface/free-surface. Setting this only makes sense
    /// if the interface is, in fact, a free surface (well,
    /// an interface to another inviscid fluid if you want to be picky).
    /// Second argument specifies the index of the pressure
    /// value within the Data object.
    void set_external_pressure_data(
      Data* external_pressure_data_pt,
      const unsigned& index_of_external_pressure_value)
    {
      // Index of pressure value in Data object
      Index_of_external_pressure_value = index_of_external_pressure_value;

#ifdef PARANOID
      if (index_of_external_pressure_value >=
          external_pressure_data_pt->nvalue())
      {
        std::ostringstream error_message;
        error_message << "External pressure Data only contains "
                      << external_pressure_data_pt->nvalue() << " values\n"
                      << "You have declared value "
                      << index_of_external_pressure_value
                      << " to be the value representing the pressure\n"
                      << std::endl;
        throw OomphLibError(error_message.str(),
                            OOMPH_CURRENT_FUNCTION,
                            OOMPH_EXCEPTION_LOCATION);
      }
#endif

      // Store pointer explicitly
      Pext_data_pt = external_pressure_data_pt;

      // Add the external pressure to the element's external Data?
      // But do not finite-difference with respect to it
      this->add_external_data(Pext_data_pt, false);

      // The external pressure has just been promoted to become
      // external Data of this element -- what is its number?
      External_data_number_of_external_pressure = this->nexternal_data() - 1;
    }


    /// Hijack the kinematic condition at the node numbers passed in
    /// the vector. The node numbers correspond to the local numbers of
    /// nodes in the associated bulk element.
    /// This is required so that contact-angle conditions can be applied
    /// by the FluidInterfaceBoundingElements.
    virtual void hijack_kinematic_conditions(
      const Vector<unsigned>& bulk_node_number)
    {
      std::ostringstream error_message;
      error_message
        << "hijack_kinematic_conditions not implemented in base "
           "FluidInterfaceElement, use one of the inherited classes depending "
           "on how the solid displacement is implemented."
        << std::endl;
      throw OomphLibError(
        error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
    }

    /// Overload the output function
    void output(std::ostream& outfile)
    {
      FiniteElement::output(outfile);
    }

    /// Output function
    void output(std::ostream& outfile, const unsigned& n_plot)
    {
      const unsigned el_dim = this->dim();
      const unsigned n_dim = this->nodal_dimension();
      const unsigned n_velocity = n_dim;
      // Set output Vector
      Vector<double> s(el_dim);

      // Tecplot header info
      outfile << this->tecplot_zone_string(n_plot);

      // Loop over plot points
      unsigned num_plot_points = this->nplot_points(n_plot);
      for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
      {
        // Get local coordinates of pliot point
        this->get_s_plot(iplot, n_plot, s);

        // Output the x,y,u,v
        for (unsigned i = 0; i < n_dim; i++)
          outfile << this->interpolated_x(s, i) << " ";
        for (unsigned i = 0; i < n_velocity; i++)
          outfile << this->interpolated_u(s, i) << " ";

        // Output a dummy pressure
        outfile << 0.0 << "\n";
      }

      this->write_tecplot_zone_footer(outfile, n_plot);

      outfile << "\n";
    }

    /// Overload the C-style output function
    void output(FILE* file_pt)
    {
      FiniteElement::output(file_pt);
    }

    /// C-style Output function
    void output(FILE* file_pt, const unsigned& n_plot)
    {
      const unsigned el_dim = this->dim();
      const unsigned n_dim = this->nodal_dimension();
      const unsigned n_velocity = n_dim;
      // Set output Vector
      Vector<double> s(el_dim);

      // Tecplot header info
      fprintf(file_pt, "%s", this->tecplot_zone_string(n_plot).c_str());

      // Loop over plot points
      unsigned num_plot_points = this->nplot_points(n_plot);
      for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
      {
        // Get local coordinates of plot point
        this->get_s_plot(iplot, n_plot, s);

        // Coordinates
        for (unsigned i = 0; i < n_dim; i++)
        {
          fprintf(file_pt, "%g ", this->interpolated_x(s, i));
        }

        // Velocities
        for (unsigned i = 0; i < n_velocity; i++)
        {
          fprintf(file_pt, "%g ", this->interpolated_u(s, i));
        }

        // Dummy Pressure
        fprintf(file_pt, "%g \n", 0.0);
      }
      fprintf(file_pt, "\n");

      // Write tecplot footer (e.g. FE connectivity lists)
      this->write_tecplot_zone_footer(file_pt, n_plot);
    }
  };


  //=============================================================
  /// Class that establishes the surface derivative functions for
  /// LineElements. These are defined in a separate class so that
  /// they can be used by other interface equation-type classes.
  //=============================================================
  class LineDerivatives
  {
  public:
    // Empty Constructor
    LineDerivatives() {}

  protected:
    /// Fill in the specific surface derivative calculations
    double compute_surface_derivatives(
      const Shape& psi,
      const DShape& dpsids,
      const DenseMatrix<double>& interpolated_t,
      const Vector<double>& interpolated_x,
      DShape& surface_gradient,
      DShape& surface_divergence);
  };


  //=============================================================
  /// Class that establishes the surface derivative functions for
  /// AxisymmetricInterfaceElements.
  /// These are defined in a separate class so that
  /// they can be used by other interface equation-type classes.
  //=============================================================
  class AxisymmetricDerivatives
  {
  public:
    // Empty Constructor
    AxisymmetricDerivatives() {}

  protected:
    /// Fill in the specific surface derivative calculations
    double compute_surface_derivatives(
      const Shape& psi,
      const DShape& dpsids,
      const DenseMatrix<double>& interpolated_t,
      const Vector<double>& interpolated_x,
      DShape& surface_gradient,
      DShape& surface_divergence);
  };


  //=============================================================
  /// Class that establishes the surface derivative functions for
  /// SurfaceInterfaceElements (2D surfaces in 3D space)
  /// These are defined in a separate class so that
  /// they can be used by other interface equation-type classes.
  //=============================================================
  class SurfaceDerivatives
  {
  public:
    // Empty Constructor
    SurfaceDerivatives() {}

  protected:
    /// Fill in the specific surface derivative calculations
    double compute_surface_derivatives(
      const Shape& psi,
      const DShape& dpsids,
      const DenseMatrix<double>& interpolated_t,
      const Vector<double>& interpolated_x,
      DShape& surface_gradient,
      DShape& surface_divergence);
  };


} // namespace oomph

#endif
