// LIC// ====================================================================
// LIC// This file forms part of oomph-lib, the object-oriented,
// LIC// multi-physics finite-element library, available
// LIC// at http://www.oomph-lib.org.
// LIC//
// LIC// Copyright (C) 2006-2022 Matthias Heil and Andrew Hazel
// LIC//
// LIC// This library is free software; you can redistribute it and/or
// LIC// modify it under the terms of the GNU Lesser General Public
// LIC// License as published by the Free Software Foundation; either
// LIC// version 2.1 of the License, or (at your option) any later version.
// LIC//
// LIC// This library is distributed in the hope that it will be useful,
// LIC// but WITHOUT ANY WARRANTY; without even the implied warranty of
// LIC// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// LIC// Lesser General Public License for more details.
// LIC//
// LIC// You should have received a copy of the GNU Lesser General Public
// LIC// License along with this library; if not, write to the Free Software
// LIC// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
// LIC// 02110-1301  USA.
// LIC//
// LIC// The authors may be contacted at oomph-lib@maths.man.ac.uk.
// LIC//
// LIC//====================================================================
// Header file for specific (two-dimensional) fluid free surface elements

// Include guards, to prevent multiple includes
#ifndef OOMPH_SPECIFIC_NODE_UPDATE_INTERFACE_ELEMENTS_HEADER
#define OOMPH_SPECIFIC_NODE_UPDATE_INTERFACE_ELEMENTS_HEADER

// Config header generated by autoconfig
#ifdef HAVE_CONFIG_H
#include <oomph-lib-config.h>
#endif

// OOMPH-LIB headers
#include "../generic/Qelements.h"
#include "../generic/spines.h"
#include "../generic/hijacked_elements.h"
#include "interface_elements.h"

namespace oomph
{
  //=======================================================================
  /// This policy class is used to associate specific bounding
  /// elements with specific FluidInterface elements. It must be filled
  /// in for every class that uses the SpineUpdateFluidInterface<...>
  /// or ElasticUpdateFluidInterface<....> generic template classes.
  /// Examples for our default Line, Axisymmetric and Surface types
  /// are included below
  //=======================================================================
  template<class ELEMENT>
  class BoundingElementType
  {
  };

  //======================================================================
  /// This policy class is used to allow additional values to be
  /// added to the nodes from new surface equations, for examples of
  /// usage see the SurfactantTransportFluidInterfaceElements.
  /// The use of this class avoids issues with calling virtual
  /// functions in constructors and avoids having a global look-up
  /// able, although it functions in much the same way.
  /// Typically, this will only be filled in by "expert users" and
  /// is only required if you want to write generic surface-element
  /// classes. Specific classes can always be overloaded on a
  /// case-by-case basis.
  //=====================================================================
  template<class ELEMENT>
  class FluidInterfaceAdditionalValues
  {
  private:
    // Issue an error message if this base class is called
    void error_message()
    {
      std::ostringstream error_message;
      error_message
        << "The generic FluidInterfaceAdditionalValues<ELEMENT> class has "
           "been\n"
        << "called. This should never happen. If you are creating your own\n"
        << "surface equations you must overload the policy class to specify\n"
        << "how many additional values are required at the surface nodes.\n"
        << "For an example, see "
           "src/fluid_interface/surfactant_transport_elements.h\n"
        << std::endl;
      throw OomphLibError(
        error_message.str(), OOMPH_CURRENT_FUNCTION, OOMPH_EXCEPTION_LOCATION);
    }

  public:
    /// Empty constructor
    FluidInterfaceAdditionalValues<ELEMENT>() {}

    /// Specific interface that states how many additional values are
    /// required for the n-th node. Default is zero, but issue error_message.
    inline unsigned nadditional_values(const unsigned& n)
    {
      error_message();
      return 0;
    }

    /// Specify any additional index setup information that is required;
    /// i.e. the look-up schemes for the additional values.
    /// Default is empty with error message
    inline void setup_equation_indices(ELEMENT* const& element_pt,
                                       const unsigned& id)
    {
      error_message();
    }
  };


  //======================================================================
  /// Specific policy class for the FluidInterfaceElemetnts,
  /// which do not require any additional values at the nodes.
  //=====================================================================
  template<class ELEMENT>
  class FluidInterfaceAdditionalValues<FluidInterfaceElement<ELEMENT>>
  {
  public:
    /// Empty constructor
    FluidInterfaceAdditionalValues<FluidInterfaceElement<ELEMENT>>() {}

    /// Specific interface that states how many additional values are
    /// required for the n-th node. No additional values
    inline unsigned nadditional_values(const unsigned& n)
    {
      return 0;
    }

    /// Specify any additional index setup information that is required;
    /// i.e. the look-up schemes for the additional values.
    /// Empty
    inline void setup_equation_indices(
      FluidInterfaceElement<ELEMENT>* const& element_pt, const unsigned& id)
    {
    }
  };


  //-------------SPINE NODE UPDATE CLASSES-------------------------------
  //---------------------------------------------------------------------

  //======================================================================
  /// Generic Spine node update interface template class that can
  /// be combined with a given surface equations class and surface
  /// derivative class to provide
  /// a concrete implementation of any surface element that uses spines.
  //======================================================================
  template<class EQUATION_CLASS, class DERIVATIVE_CLASS, class ELEMENT>
  class SpineUpdateFluidInterfaceElement
    : public virtual Hijacked<SpineElement<FaceGeometry<ELEMENT>>>,
      public virtual EQUATION_CLASS,
      public DERIVATIVE_CLASS
  {
  private:
    /// In spine elements, the kinematic condition is the equation
    /// used to determine the unknown spine heights. Overload the
    /// function accordingly
    int kinematic_local_eqn(const unsigned& n)
    {
      return this->spine_local_eqn(n);
    }

    /// Hijacking the kinematic condition corresponds to hijacking the
    /// variables associated with the spine heights.
    void hijack_kinematic_conditions(const Vector<unsigned>& bulk_node_number)
    {
      // Loop over all the node numbers that are passed in
      for (Vector<unsigned>::const_iterator it = bulk_node_number.begin();
           it != bulk_node_number.end();
           ++it)
      {
        // Hijack the spine heights. (and delete the returned data object)
        delete this->hijack_nodal_spine_value(*it, 0);
      }
    }

  protected:
    /// Fill in the specific surface derivative calculations
    /// by calling the appropriate class function
    double compute_surface_derivatives(
      const Shape& psi,
      const DShape& dpsids,
      const DenseMatrix<double>& interpolated_t,
      const Vector<double>& interpolated_x,
      DShape& surface_gradient,
      DShape& surface_divergence)
    {
      return DERIVATIVE_CLASS::compute_surface_derivatives(psi,
                                                           dpsids,
                                                           interpolated_t,
                                                           interpolated_x,
                                                           surface_gradient,
                                                           surface_divergence);
    }


  public:
    /// Constructor, the arguments are a pointer to the  "bulk" element
    /// and the index of the face to be created
    SpineUpdateFluidInterfaceElement(FiniteElement* const& element_pt,
                                     const int& face_index,
                                     const unsigned& id = 0)
      : Hijacked<SpineElement<FaceGeometry<ELEMENT>>>(),
        EQUATION_CLASS(),
        DERIVATIVE_CLASS()
    {
      // Attach the geometrical information to the element, by
      // making the face element from the bulk element
      element_pt->build_face_element(face_index, this);

#ifdef PARANOID
      // Is it refineable
      RefineableElement* ref_el_pt =
        dynamic_cast<RefineableElement*>(element_pt);
      if (ref_el_pt != 0)
      {
        if (this->has_hanging_nodes())
        {
          throw OomphLibError("This interface element will not work correctly "
                              "if nodes are hanging\n",
                              OOMPH_CURRENT_FUNCTION,
                              OOMPH_EXCEPTION_LOCATION);
        }
      }
#endif

      // Read out the number of nodes on the face
      const unsigned n_node_face = this->nnode();

      // Find the index at which the velocity unknowns are stored
      // from the bulk element and allocate the local storage
      ELEMENT* cast_element_pt = dynamic_cast<ELEMENT*>(element_pt);

      // Add any additional values required by the equations class
      // Create an instance of the policy class that determines
      // how many additional values are required
      FluidInterfaceAdditionalValues<EQUATION_CLASS>*
        interface_additional_values_pt =
          new FluidInterfaceAdditionalValues<EQUATION_CLASS>();
      // Do we need to add any values
      // By default the spines don't need to so we can save
      // some effort here
      bool add_values = false;
      // Storage for the number of additional values required
      // for each node
      Vector<unsigned> additional_data_values(n_node_face);
      for (unsigned i = 0; i < n_node_face; ++i)
      {
        // Read out additional values for each node
        additional_data_values[i] =
          interface_additional_values_pt->nadditional_values(i);
        // If any of these are non-zero it will set the boolean to true
        add_values |= additional_data_values[i];
      }

      // If storage is needed allocate it and call
      // the associated local index setup function
      if (add_values)
      {
        this->add_additional_values(additional_data_values, id);
        // Call any local setup from the interface policy class
        interface_additional_values_pt->setup_equation_indices(this, id);
      }

      // Delete the policy class, it's work is done.
      delete interface_additional_values_pt;
      interface_additional_values_pt = 0;
    }

    /// Calculate the contribution to the residuals and the jacobian
    void fill_in_contribution_to_jacobian(Vector<double>& residuals,
                                          DenseMatrix<double>& jacobian)
    {
      // Call the generic routine with the flag set to 1
      EQUATION_CLASS::fill_in_generic_residual_contribution_interface(
        residuals, jacobian, 1);

      // Call the generic routine to handle the shape derivatives
      this->fill_in_jacobian_from_geometric_data(jacobian);
    }

    /// \short
    /// Helper function to calculate the additional contributions
    /// These are those filled in by the particular equations
    void add_additional_residual_contributions_interface(
      Vector<double>& residuals,
      DenseMatrix<double>& jacobian,
      const unsigned& flag,
      const Shape& psif,
      const DShape& dpsifds,
      const DShape& dpsifdS,
      const DShape& dpsifdS_div,
      const Vector<double>& s,
      const Vector<double>& interpolated_x,
      const Vector<double>& interpolated_n,
      const double& W,
      const double& J)
    {
      EQUATION_CLASS::add_additional_residual_contributions_interface(
        residuals,
        jacobian,
        flag,
        psif,
        dpsifds,
        dpsifdS,
        dpsifdS_div,
        s,
        interpolated_x,
        interpolated_n,
        W,
        J);
    }

    /// Overload the output function
    void output(std::ostream& outfile)
    {
      EQUATION_CLASS::output(outfile);
    }

    /// Output the element
    void output(std::ostream& outfile, const unsigned& n_plot)
    {
      EQUATION_CLASS::output(outfile, n_plot);
    }

    /// Overload the C-style output function
    void output(FILE* file_pt)
    {
      EQUATION_CLASS::output(file_pt);
    }

    /// C-style Output function
    void output(FILE* file_pt, const unsigned& n_plot)
    {
      EQUATION_CLASS::output(file_pt, n_plot);
    }
  };


  //=====================================================================
  /// Spine version of the PointFluidInterfaceBoundingElement
  //=====================================================================
  template<class ELEMENT>
  class SpineFluidInterfaceBoundingElement
    : public Hijacked<SpineElement<FaceGeometry<ELEMENT>>>,
      public FluidInterfaceBoundingElement<ELEMENT>

  {
  public:
    /// Constructor
    SpineFluidInterfaceBoundingElement()
      : Hijacked<SpineElement<FaceGeometry<ELEMENT>>>(),
        FluidInterfaceBoundingElement<ELEMENT>()
    {
    }

    /// Overload the output function
    void output(std::ostream& outfile)
    {
      FiniteElement::output(outfile);
    }

    /// Output the element
    void output(std::ostream& outfile, const unsigned& n_plot)
    {
      FluidInterfaceBoundingElement<ELEMENT>::output(outfile, n_plot);
    }

    /// Overload the C-style output function
    void output(FILE* file_pt)
    {
      FiniteElement::output(file_pt);
    }

    /// C-style Output function
    void output(FILE* file_pt, const unsigned& n_plot)
    {
      FluidInterfaceBoundingElement<ELEMENT>::output(file_pt, n_plot);
    }

    /// Calculate the elemental residual vector and the Jacobian
    void fill_in_contribution_to_jacobian(Vector<double>& residuals,
                                          DenseMatrix<double>& jacobian)
    {
      // Call the generic routine with the flag set to 1
      this->fill_in_generic_residual_contribution_interface_boundary(
        residuals, jacobian, 1);
      // Call generic FD routine for the external data
      this->fill_in_jacobian_from_external_by_fd(jacobian);

      // Call the generic routine to handle the spine variables
      this->fill_in_jacobian_from_geometric_data(jacobian);
    }
  };


  //============GEOMETRIC SPECIALISATIONS============================


  // Specialise the spine update template class to concrete 1D case
  template<class ELEMENT>
  class SpineLineFluidInterfaceElement
    : public SpineUpdateFluidInterfaceElement<FluidInterfaceElement<ELEMENT>,
                                              LineDerivatives,
                                              ELEMENT>
  {
  public:
    SpineLineFluidInterfaceElement(FiniteElement* const& element_pt,
                                   const int& face_index)
      : SpineUpdateFluidInterfaceElement<FluidInterfaceElement<ELEMENT>,
                                         LineDerivatives,
                                         ELEMENT>(element_pt, face_index)
    {
    }
  };


  // Define the BoundingElement type associated with the 1D surface element
  template<class ELEMENT>
  class BoundingElementType<
    SpineUpdateFluidInterfaceElement<FluidInterfaceElement<ELEMENT>,
                                     LineDerivatives,
                                     ELEMENT>>
    : public SpineFluidInterfaceBoundingElement<ELEMENT>
  {
  public:
    BoundingElementType<
      SpineUpdateFluidInterfaceElement<FluidInterfaceElement<ELEMENT>,
                                       LineDerivatives,
                                       ELEMENT>>()
      : SpineFluidInterfaceBoundingElement<ELEMENT>()
    {
    }
  };


  // Specialise Spine update case to concrete axisymmetric case
  template<class ELEMENT>
  class SpineAxisymmetricFluidInterfaceElement
    : public SpineUpdateFluidInterfaceElement<FluidInterfaceElement<ELEMENT>,
                                              AxisymmetricDerivatives,
                                              ELEMENT>
  {
  public:
    SpineAxisymmetricFluidInterfaceElement(FiniteElement* const& element_pt,
                                           const int& face_index)
      : SpineUpdateFluidInterfaceElement<FluidInterfaceElement<ELEMENT>,
                                         AxisymmetricDerivatives,
                                         ELEMENT>(element_pt, face_index)
    {
    }
  };

  // Define the bounding element associated with the axisymmetric fluid
  // interface element
  template<class ELEMENT>
  class BoundingElementType<
    SpineUpdateFluidInterfaceElement<FluidInterfaceElement<ELEMENT>,
                                     AxisymmetricDerivatives,
                                     ELEMENT>>
    : public SpineFluidInterfaceBoundingElement<ELEMENT>
  {
  public:
    BoundingElementType<
      SpineUpdateFluidInterfaceElement<FluidInterfaceElement<ELEMENT>,
                                       AxisymmetricDerivatives,
                                       ELEMENT>>()
      : SpineFluidInterfaceBoundingElement<ELEMENT>()
    {
    }
  };

  // Specialise Spine update case to concrete 2D case
  template<class ELEMENT>
  class SpineSurfaceFluidInterfaceElement
    : public SpineUpdateFluidInterfaceElement<FluidInterfaceElement<ELEMENT>,
                                              SurfaceDerivatives,
                                              ELEMENT>
  {
  public:
    SpineSurfaceFluidInterfaceElement(FiniteElement* const& element_pt,
                                      const int& face_index)
      : SpineUpdateFluidInterfaceElement<FluidInterfaceElement<ELEMENT>,
                                         SurfaceDerivatives,
                                         ELEMENT>(element_pt, face_index)
    {
    }
  };


  /// ////////////////////////////////////////////////////////////////////
  /// ////////////////////////////////////////////////////////////////////
  /// ////////////////////////////////////////////////////////////////////

  //-------------ELASTIC NODE UPDATE CLASSES-------------------------------
  //---------------------------------------------------------------------


  //=======================================================================
  /// Generic Elastic node update interface template class that can
  /// be combined with a given surface equations class and surface derivative
  /// class to provide a concrete implementation of any surface element
  /// that uses elastic node updates.
  //======================================================================
  template<class EQUATION_CLASS, class DERIVATIVE_CLASS, class ELEMENT>
  class ElasticUpdateFluidInterfaceElement
    : public virtual Hijacked<NavierStokesFaceElement<ELEMENT>>,
      public EQUATION_CLASS,
      public DERIVATIVE_CLASS
  {
  private:
    /// Storage for the location of the Lagrange multiplier
    /// (If other additional values have been added we need
    /// to add the Lagrange multiplier at the end)
    Vector<unsigned> Lagrange_index;

    /// Return the index at which the lagrange multiplier is
    /// stored at the n-th node
    inline unsigned lagrange_index(const unsigned& n)
    {
      return this->Lagrange_index[n];
    }

    /// Equation number of the kinematic BC associated with node j.
    /// (This is the equation for the Lagrange multiplier)
    inline int kinematic_local_eqn(const unsigned& n)
    {
      // Get the index of the nodal value associated with Lagrange multiplier
      return this->nodal_local_eqn(n, this->lagrange_index(n));
    }

    /// Hijacking the kinematic condition corresponds to hijacking the
    /// variables associated with the Lagrange multipliers that are assigned
    /// on construction of this element.
    void hijack_kinematic_conditions(const Vector<unsigned>& bulk_node_number)
    {
      // Loop over all the nodes that are passed in
      for (Vector<unsigned>::const_iterator it = bulk_node_number.begin();
           it != bulk_node_number.end();
           ++it)
      {
        // Hijack the appropriate value and delete the returned Node
        delete this->hijack_nodal_value(*it, this->lagrange_index(*it));
      }
    }

  protected:
    /// Fill in the specific surface derivative calculations
    /// by calling the appropriate function from the derivative class
    double compute_surface_derivatives(
      const Shape& psi,
      const DShape& dpsids,
      const DenseMatrix<double>& interpolated_t,
      const Vector<double>& interpolated_x,
      DShape& surface_gradient,
      DShape& surface_divergence)
    {
      return DERIVATIVE_CLASS::compute_surface_derivatives(psi,
                                                           dpsids,
                                                           interpolated_t,
                                                           interpolated_x,
                                                           surface_gradient,
                                                           surface_divergence);
    }


  public:
    /// Constructor, pass a pointer to the bulk element and the face
    /// index of the bulk element to which the element is to be attached to.
    /// The optional identifier can be used
    /// to distinguish the additional nodal value (Lagr mult) created by
    /// this element from those created by other FaceElements.
    ElasticUpdateFluidInterfaceElement(FiniteElement* const& element_pt,
                                       const int& face_index,
                                       const unsigned& id = 0)
      : FaceGeometry<NavierStokesFaceElement>(element_pt, face_index),
        EQUATION_CLASS(element_pt, face_index),
        DERIVATIVE_CLASS()
    {
      // Find the index at which the velocity unknowns are stored
      // from the bulk element and resize the local storage scheme
      ELEMENT* cast_element_pt = dynamic_cast<ELEMENT*>(element_pt);

      // Create an instance of the policy class that determines
      // how many additional values are required
      FluidInterfaceAdditionalValues<EQUATION_CLASS>*
        interface_additional_values_pt =
          new FluidInterfaceAdditionalValues<EQUATION_CLASS>();

      // Read out the number of nodes on the face
      const unsigned n_node_face = this->nnode();

      // Set the additional data values in the face
      // There is always also one additional values at each node --- the
      // Lagrange multiplier
      Vector<unsigned> additional_data_values(n_node_face);
      for (unsigned n = 0; n < n_node_face; n++)
      {
        // Now add one to the addtional values at every single node
        additional_data_values[n] =
          interface_additional_values_pt->nadditional_values(n) + 1;
      }

      // Now add storage for Lagrange multipliers and set the map containing
      // the position of the first entry of this face element's
      // additional values.
      this->add_additional_values(additional_data_values, id);

      // Now I can just store the lagrange index offset to give the storage
      // location of the nodes
      Lagrange_index.resize(n_node_face);
      for (unsigned n = 0; n < n_node_face; ++n)
      {
        Lagrange_index[n] =
          additional_data_values[n] - 1 +
          dynamic_cast<BoundaryNodeBase*>(this->node_pt(n))
            ->index_of_first_value_assigned_by_face_element(id);
      }

      // Call any local setup from the interface policy class
      interface_additional_values_pt->setup_equation_indices(this, id);

      // Can now delete the policy class
      delete interface_additional_values_pt;
      interface_additional_values_pt = 0;
    }

    /// The "global" intrinsic coordinate of the element when
    /// viewed as part of a geometric object should be given by
    /// the FaceElement representation, by default
    double zeta_nodal(const unsigned& n,
                      const unsigned& k,
                      const unsigned& i) const
    {
      return FaceElement::zeta_nodal(n, k, i);
    }

    /// Return the lagrange multiplier at local node n
    double& lagrange(const unsigned& n)
    {
      return *this->node_pt(n)->value_pt(this->lagrange_index(n));
    }

    /// Return the lagrange multiplier at local node n
    double interpolated_lagrange(const Vector<double>& s)
    {
      // Find number of nodes
      unsigned n_node = FiniteElement::nnode();

      // Storage for the local shape function
      Shape psi(n_node);

      // Get values of shape function at local coordinate s
      this->shape(s, psi);

      // Initialise value of lambda
      double interpolated_lambda = 0.0;

      // Loop over the local nodes and sum
      for (unsigned l = 0; l < n_node; l++)
      {
        interpolated_lambda +=
          *this->node_pt(l)->value_pt(this->lagrange_index(l)) * psi(l);
      }

      return (interpolated_lambda);
    }


    void fix_lagrange_multiplier(const unsigned& n, const double& value)
    {
      this->node_pt(n)->pin(this->lagrange_index(n));
      this->node_pt(n)->set_value(this->lagrange_index(n), value);
    }

    void free_lagrange_multiplier(const unsigned& n)
    {
      this->node_pt(n)->unpin(this->lagrange_index(n));
    }


    /// Fill in contribution to residuals and Jacobian
    // void fill_in_contribution_to_jacobian(Vector<double>& residuals,
    //                                      DenseMatrix<double>& jacobian)
    //{
    //  // Call the generic routine with the flag set to 1
    //  EQUATION_CLASS::fill_in_generic_residual_contribution_interface(
    //    residuals, jacobian, 1);

    //  // Call the generic finite difference routine for the solid variables
    //  this->fill_in_jacobian_from_solid_position_by_fd(jacobian);
    //}

    /// Overload the output function
    void output(std::ostream& outfile)
    {
      EQUATION_CLASS::output(outfile);
    }

    /// Output the element
    void output(std::ostream& outfile, const unsigned& n_plot)
    {
      const unsigned el_dim = this->dim();
      const unsigned n_dim = this->nodal_dimension();
      const unsigned n_velocity = n_dim;
      // Set output Vector
      Vector<double> s(el_dim);

      // Loop over plot points
      unsigned num_plot_points = this->nplot_points(n_plot);
      for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
      {
        // Get local coordinates of pliot point
        this->get_s_plot(iplot, n_plot, s);

        // Output the x,y,u,v
        for (unsigned i = 0; i < n_dim; i++)
          outfile << this->interpolated_x(s, i) << ",";
        for (unsigned i = 0; i < n_velocity; i++)
          outfile << this->interpolated_u(s, i) << ",";

        // Output a dummy pressure
        outfile << 0.0 << ",";

        // Output the lagrange multiplier
        outfile << interpolated_lagrange(s) << "\n";
      }
      outfile << "\n";
    }

    /// Overload the C-style output function
    void output(FILE* file_pt)
    {
      EQUATION_CLASS::output(file_pt);
    }

    /// C-style Output function
    void output(FILE* file_pt, const unsigned& n_plot)
    {
      const unsigned el_dim = this->dim();
      const unsigned n_dim = this->nodal_dimension();
      const unsigned n_velocity = n_dim;
      // Set output Vector
      Vector<double> s(el_dim);

      // Tecplot header info
      fprintf(file_pt, "%s", this->tecplot_zone_string(n_plot).c_str());

      // Loop over plot points
      unsigned num_plot_points = this->nplot_points(n_plot);
      for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
      {
        // Get local coordinates of plot point
        this->get_s_plot(iplot, n_plot, s);

        // Coordinates
        for (unsigned i = 0; i < n_dim; i++)
        {
          fprintf(file_pt, "%g ", this->interpolated_x(s, i));
        }

        // Velocities
        for (unsigned i = 0; i < n_velocity; i++)
        {
          fprintf(file_pt, "%g ", this->interpolated_u(s, i));
        }

        // Dummy Pressure
        fprintf(file_pt, "%g \n", 0.0);
      }
      fprintf(file_pt, "\n");

      // Write tecplot footer (e.g. FE connectivity lists)
      this->write_tecplot_zone_footer(file_pt, n_plot);
    }


    /// Helper function to calculate the additional contributions
    /// to be added at each integration point. This deals with
    /// Lagrange multiplier contribution, as well as any
    /// additional contributions by the other equations.
    void add_additional_residual_contributions_interface(
      Vector<double>& residuals,
      DenseMatrix<double>& jacobian,
      const unsigned& flag,
      const Shape& psif,
      const DShape& dpsifds,
      const DShape& dpsifdS,
      const DShape& dpsifdS_div,
      const Vector<double>& s,
      const Vector<double>& interpolated_x,
      const Vector<double>& interpolated_n,
      const double& W,
      const double& J)
    {
      EQUATION_CLASS::add_additional_residual_contributions_interface(
        residuals,
        jacobian,
        flag,
        psif,
        dpsifds,
        dpsifdS,
        dpsifdS_div,
        s,
        interpolated_x,
        interpolated_n,
        W,
        J);

      // Assemble Lagrange multiplier by loop over the shape functions
      const unsigned n_node = this->nnode();
      // Read out the dimension of the node
      const unsigned nodal_dimension = this->nodal_dimension();

      double interpolated_lagrange = 0.0;
      for (unsigned l = 0; l < n_node; l++)
      {
        // Note same shape functions used for lagrange multiplier field
        interpolated_lagrange += lagrange(l) * psif(l);
      }

      int local_eqn = 0;

      // Loop over the shape functions to assemble contributions
      for (unsigned l = 0; l < n_node; l++)
      {
        // Loop over the directions
        for (unsigned i = 0; i < nodal_dimension; i++)
        {
          // Kinematic Lagrange multiplier Momentum contribution
          local_eqn = this->nodal_local_eqn(l, this->U_index_interface[l][i]);
          if (local_eqn >= 0)
          {
            residuals[local_eqn] +=
              interpolated_lagrange * interpolated_n[i] * psif(l) * J * W;

            // Do the Jacobian calculation
            if (flag)
            {
              throw OomphLibError("Not yet implemented\n",
                                  OOMPH_CURRENT_FUNCTION,
                                  OOMPH_EXCEPTION_LOCATION);
            }
          }


          // Kinematic Lagrange multiplier Solid displacement contribution

          // Now using the same shape functions for the elastic equations,
          // so we can stay in the loop
          local_eqn = this->position_local_eqn(l, 0, i);
          if (local_eqn >= 0)
          {
            // Add in the Lagrange multiplier contribution
            if (this->node_pt(l)->time_stepper_pt()->weight(1, 0) > 0)
            {
              residuals[local_eqn] -=
                interpolated_lagrange * this->st() *
                this->node_pt(l)->time_stepper_pt()->weight(1, 0) *
                interpolated_n[i] * psif(l) * J * W;
            }
            else
            {
              residuals[local_eqn] -=
                interpolated_lagrange * interpolated_n[i] * psif(l) * J * W;
            }
            // Do the Jacobian calculation
            if (flag)
            {
              throw OomphLibError("Not yet implemented\n",
                                  OOMPH_CURRENT_FUNCTION,
                                  OOMPH_EXCEPTION_LOCATION);
              //// Loop over the nodes
              // for (unsigned l2 = 0; l2 < n_node; l2++)
              //{
              //  // Dependence on solid positions will be handled by FDs
              //  // That leaves the Lagrange multiplier contribution
              //  local_unknown = this->kinematic_local_eqn(l2);
              //  if (local_unknown >= 0)
              //  {
              //    jacobian(local_eqn, local_unknown) -=
              //      psif(l2) * interpolated_n[i] * psif(l) * J * W;
              //  }
              //}
            } // End of Jacobian calculation
          }
        }
      } // End of loop over shape functions
    }
  };


  //=========================================================================
  /// Pseudo-elasticity version of the PointFluidInterfaceBoundingElement
  //========================================================================
  template<class ELEMENT>
  class ElasticFluidInterfaceBoundingElement
    : public FluidInterfaceBoundingElement<ELEMENT>,
      public virtual SolidFiniteElement

  {
  private:
    /// Short Storage for the index of the Lagrange multiplier at the chosen
    /// nodes
    Vector<unsigned> Lagrange_index;

  public:
    /// Set the Id and offset
    void set_lagrange_index(const Vector<unsigned>& lagrange_index)
    {
      Lagrange_index = lagrange_index;
    }

    /// Specify the value of nodal zeta from the face geometry
    /// The "global" intrinsic coordinate of the element when
    /// viewed as part of a geometric object should be given by
    /// the FaceElement representation, by default
    double zeta_nodal(const unsigned& n,
                      const unsigned& k,
                      const unsigned& i) const
    {
      return FaceElement::zeta_nodal(n, k, i);
    }


    /// Constructor
    ElasticFluidInterfaceBoundingElement()
      : FluidInterfaceBoundingElement<ELEMENT>()
    {
    }

    /// Overload the output function
    void output(std::ostream& outfile)
    {
      FluidInterfaceBoundingElement<ELEMENT>::output(outfile);
    }

    /// Output the element
    void output(std::ostream& outfile, const unsigned& n_plot)
    {
      FluidInterfaceBoundingElement<ELEMENT>::output(outfile, n_plot);
    }

    /// Overload the C-style output function
    void output(FILE* file_pt)
    {
      FiniteElement::output(file_pt);
    }

    /// C-style Output function
    void output(FILE* file_pt, const unsigned& n_plot)
    {
      FluidInterfaceBoundingElement<ELEMENT>::output(file_pt, n_plot);
    }

    /// Calculate the element's residual vector and Jacobian
    // void fill_in_contribution_to_jacobian(Vector<double>& residuals,
    //                                      DenseMatrix<double>& jacobian)
    //{
    //  // Call the generic routine with the flag set to 1
    //  fill_in_generic_residual_contribution_interface_boundary(
    //    residuals, jacobian, 0);

    //  // Call the generic FD routine to get internal data
    //  this->fill_in_jacobian_from_internal_by_fd(jacobian);

    //  // Call the generic FD routine to get external data
    //  this->fill_in_jacobian_from_external_by_fd(jacobian);

    //  // Call the generic finite difference routine to handle the solid
    //  // variables
    //  this->fill_in_jacobian_from_solid_position_by_fd(jacobian);
    //}

    /// Set the kinematic local equation
    inline int kinematic_local_eqn(const unsigned& n)
    {
      return this->position_local_eqn(n, 0, 1); // TODO fix!
      // return this->nodal_local_eqn(n, this->Lagrange_index[n]);
    }
  };


  //==================GEOMETRIC SPECIALISATIONS==========================


  /// Specialise the elastic update template class to concrete 1D case
  template<class ELEMENT>
  class ElasticLineFluidInterfaceElement
    : public ElasticUpdateFluidInterfaceElement<FluidInterfaceElement,
                                                LineDerivatives,
                                                ELEMENT>
  {
  public:
    ElasticLineFluidInterfaceElement(FiniteElement* const& element_pt,
                                     const int& face_index,
                                     const unsigned& id = 0)
      : ElasticUpdateFluidInterfaceElement<FluidInterfaceElement,
                                           LineDerivatives,
                                           ELEMENT>(element_pt, face_index, id)
    {
    }
  };

  /// Define the BoundingElement type associated with the 1D surface element
  template<class ELEMENT>
  class BoundingElementType<
    ElasticUpdateFluidInterfaceElement<FluidInterfaceElement<ELEMENT>,
                                       LineDerivatives,
                                       ELEMENT>>
    : public ElasticFluidInterfaceBoundingElement<ELEMENT>
  {
  public:
    BoundingElementType<
      ElasticUpdateFluidInterfaceElement<FluidInterfaceElement<ELEMENT>,
                                         LineDerivatives,
                                         ELEMENT>>()
      : ElasticFluidInterfaceBoundingElement<ELEMENT>()
    {
    }
  };


  /// Specialise the Elastic update case to axisymmetric equations
  template<class ELEMENT>
  class ElasticAxisymmetricFluidInterfaceElement
    : public ElasticUpdateFluidInterfaceElement<FluidInterfaceElement<ELEMENT>,
                                                AxisymmetricDerivatives,
                                                ELEMENT>
  {
  public:
    ElasticAxisymmetricFluidInterfaceElement(FiniteElement* const& element_pt,
                                             const int& face_index,
                                             const unsigned& id = 0)
      : ElasticUpdateFluidInterfaceElement<FluidInterfaceElement<ELEMENT>,
                                           AxisymmetricDerivatives,
                                           ELEMENT>(element_pt, face_index, id)
    {
    }
  };

  /// Specialise Elastic update case to the concrete 2D case
  template<class ELEMENT>
  class ElasticSurfaceFluidInterfaceElement
    : public ElasticUpdateFluidInterfaceElement<FluidInterfaceElement<ELEMENT>,
                                                SurfaceDerivatives,
                                                ELEMENT>
  {
  public:
    ElasticSurfaceFluidInterfaceElement(FiniteElement* const& element_pt,
                                        const int& face_index,
                                        const unsigned& id = 0)
      : ElasticUpdateFluidInterfaceElement<FluidInterfaceElement<ELEMENT>,
                                           SurfaceDerivatives,
                                           ELEMENT>(element_pt, face_index, id)
    {
    }
  };


} // namespace oomph

#endif
