// LIC// ====================================================================
// LIC// This file forms part of oomph-lib, the object-oriented,
// LIC// multi-physics finite-element library, available
// LIC// at http://www.oomph-lib.org.
// LIC//
// LIC// Copyright (C) 2006-2024 Matthias Heil and Andrew Hazel
// LIC//
// LIC// This library is free software; you can redistribute it and/or
// LIC// modify it under the terms of the GNU Lesser General Public
// LIC// License as published by the Free Software Foundation; either
// LIC// version 2.1 of the License, or (at your option) any later version.
// LIC//
// LIC// This library is distributed in the hope that it will be useful,
// LIC// but WITHOUT ANY WARRANTY; without even the implied warranty of
// LIC// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// LIC// Lesser General Public License for more details.
// LIC//
// LIC// You should have received a copy of the GNU Lesser General Public
// LIC// License along with this library; if not, write to the Free Software
// LIC// Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
// LIC// 02110-1301  USA.
// LIC//
// LIC// The authors may be contacted at oomph-lib@maths.man.ac.uk.
// LIC//
// LIC//====================================================================
#ifndef DECOMPOSED_NO_PENETRATION_ELEMENTS_HEADER
#define DECOMPOSED_NO_PENETRATION_ELEMENTS_HEADER

// Config header generated by autoconfig
#ifdef HAVE_CONFIG_H
#include <oomph-lib-config.h>
#endif

#include <iostream>
#include "generic/nodes.h"
#include "generic/Vector.h"
#include "generic/elements.h"
#include "axisym_navier_stokes/axisym_navier_stokes_face_elements.h"

namespace oomph
{
  //========================================================================
  ///  AxisymmetricImposeImpenetrabilityElement
  /// are elements that coincide with the faces of
  /// higher-dimensional "bulk" elements. They are used on
  /// boundaries where we would like to impose impenetrability.
  //========================================================================
  template<class ELEMENT>
  class DecomposedAxisymmetricImposeImpenetrabilityElement
    : public virtual FaceGeometry<ELEMENT>,
      public virtual AxisymmetricNavierStokesFaceElement
  {
  private:
    /// Lagrange Id
    unsigned Id;

  public:
    /// Constructor takes a "bulk" element, the
    /// index that identifies which face the
    /// AxisymmetricImposeImpenetrabilityElement is supposed
    /// to be attached to, and the face element ID
    DecomposedAxisymmetricImposeImpenetrabilityElement(
      FiniteElement* const& element_pt,
      const int& face_index,
      const unsigned& id = 0)
      : FaceGeometry<ELEMENT>(), AxisymmetricNavierStokesFaceElement()
    {
      //  set the Id
      Id = id;

      // Build the face element
      element_pt->build_face_element(face_index, this);

      // we need 1 additional values for each FaceElement node
      Vector<unsigned> n_additional_values(nnode(), 2);

      // add storage for lagrange multipliers and set the map containing
      // the position of the first entry of this face element's
      // additional values.
      add_additional_values(n_additional_values, id);


      // Loop over nodes and pin the additional values by default
      for (unsigned n = 0; n < this->nnode(); n++)
      {
        for (unsigned j = 0; j < n_additional_values[n]; j++)
        {
          BoundaryNodeBase* bnod_pt =
            dynamic_cast<BoundaryNodeBase*>(this->node_pt(n));
          unsigned first_index =
            bnod_pt->index_of_first_value_assigned_by_face_element(Id);
          this->node_pt(n)->pin(first_index + j);
        }
      }
    }

    /// Return the i-th velocity component at local node j.
    virtual double u(const unsigned& j,
                     const unsigned& i,
                     const unsigned& cosine_index)
    {
      // 4 displacement dofs
      // 2 velocity dofs for each direction
      // cosine index determines whether the cosine (0) or sine (1) is used
      return nodal_value(j, 4 + 2 * i + cosine_index);
    }

    /// Calculate the i-th velocity component at the local coordinate s.
    double interpolated_u(const Vector<double>& s,
                          const unsigned& i,
                          const unsigned& cosine_index)
    {
      // Find number of nodes
      unsigned n_node = FiniteElement::nnode();

      // Storage for the local shape function
      Shape psi(n_node);

      // Get values of shape function at local coordinate s
      this->shape(s, psi);

      // Initialise value of u
      double interpolated_u = 0.0;

      // Loop over the local nodes and sum
      for (unsigned l = 0; l < n_node; l++)
      {
        interpolated_u += u(l, i, cosine_index) * psi(l);
      }

      return (interpolated_u);
    }

    /// Get the nodal index of the lagrange multiplier
    const unsigned lagrange_multiplier_index(const unsigned& n,
                                             const unsigned& j)
    {
      // Cast to a boundary node
      BoundaryNodeBase* bnod_pt = dynamic_cast<BoundaryNodeBase*>(node_pt(n));

      // Get the index of the first nodal value associated with
      // this FaceElement
      return bnod_pt->index_of_first_value_assigned_by_face_element(Id) + j;
    }

    /// Pin the lagrange multiplier at node n
    void pin_lagrange_multiplier(const unsigned& n, const unsigned& j)
    {
      this->node_pt(n)->pin(lagrange_multiplier_index(n, j));
    }

    /// Unpin the lagrange multiplier at node n
    void unpin_lagrange_multiplier(const unsigned& n, const unsigned& j)
    {
      this->node_pt(n)->unpin(lagrange_multiplier_index(n, j));
    }

    /// Set the lagrange multiplier at node n
    void set_lagrange_multiplier(const unsigned& n,
                                 const unsigned& j,
                                 const double& value)
    {
      this->node_pt(n)->set_value(lagrange_multiplier_index(n, j), value);
    }

    /// Fill in the residuals
    void fill_in_contribution_to_residuals(Vector<double>& residuals)
    {
      // Call the generic routine with the flag set to 0
      fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(
        residuals, GeneralisedElement::Dummy_matrix, 0);
    }

    /// Fill in contribution from Jacobian
    void fill_in_contribution_to_jacobian(Vector<double>& residuals,
                                          DenseMatrix<double>& jacobian)
    {
      // Call the generic routine with the flag set to 1
      fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(
        residuals, jacobian, 1);
    }

    void fill_in_contribution_to_jacobian_and_mass_matrix(
      Vector<double>& residuals,
      DenseMatrix<double>& jacobian,
      DenseMatrix<double>& mass_matrix)
    {
      fill_in_contribution_to_jacobian(residuals, jacobian);
    }

    /// Overload the output function
    void output(std::ostream& outfile)
    {
      FiniteElement::output(outfile);
    }

    /// Output function: x,y,[z],u,v,[w],p in tecplot format
    void output(std::ostream& outfile, const unsigned& nplot)
    {
      // Vector of local coordinates
      Vector<double> s(this->dim());

      // Loop over plot points
      unsigned num_plot_points = this->nplot_points(nplot);
      for (unsigned iplot = 0; iplot < num_plot_points; iplot++)
      {
        // Get local coordinates of plot point
        this->get_s_plot(iplot, nplot, s);

        // Coordinates
        for (unsigned i = 0; i < this->dim() + 1; i++)
        {
          outfile << this->interpolated_x(s, i) << " ";
        }

        // Velocities
        for (unsigned j = 0; j < 2; j++)
        {
          for (unsigned i = 0; i < this->dim() + 1; i++)
          {
            outfile << this->interpolated_u(s, i, j) << " ";
          }
        }

        // Lagrange multipliers
        for (unsigned j = 0; j < 2; j++)
        {
          outfile << interpolated_lambda(s, j) << " ";
        }

        // compute the normal vector
        Vector<double> norm_vec(this->dim() + 1);
        outer_unit_normal(iplot, norm_vec);
        for (unsigned i = 0; i < this->dim() + 1; i++)
        {
          outfile << norm_vec[i] << " ";
        }

        outfile << "\n";
      }
    }

    /// The "global" intrinsic coordinate of the element when
    /// viewed as part of a geometric object should be given by
    /// the FaceElement representation, by default
    /// This final over-ride is required because both SolidFiniteElements
    /// and FaceElements overload zeta_nodal
    double zeta_nodal(const unsigned& n,
                      const unsigned& k,
                      const unsigned& i) const
    {
      return FaceElement::zeta_nodal(n, k, i);
    }

  protected:
    /// Helper function to compute the residuals and, if flag==1, the
    /// Jacobian
    void fill_in_generic_contribution_to_residuals_parall_lagr_multiplier(
      Vector<double>& residuals,
      DenseMatrix<double>& jacobian,
      const unsigned& flag)
    {
      // Find out how many nodes there are
      unsigned n_node = nnode();

      // Dimension of element
      unsigned dim_el = dim();

      // Set up memory for the shape functions
      Shape psi(n_node);

      // Set the value of n_intpt
      unsigned n_intpt = integral_pt()->nweight();

      // to store local equation number
      int local_eqn = 0;
      int local_unknown = 0;

      // to store normal vector
      Vector<double> norm_vec(dim_el + 1);


      // Loop over the integration points
      for (unsigned ipt = 0; ipt < n_intpt; ipt++)
      {
        // Get the integral weight
        double w = integral_pt()->weight(ipt);

        // Jacobian of mapping
        double J = J_eulerian_at_knot(ipt);

        // Premultiply the weights and the Jacobian
        double W = w * J;

        // Calculate the shape functions
        shape_at_knot(ipt, psi);

        double r = 0.0;
        for (unsigned l = 0; l < n_node; l++)
        {
          r += this->nodal_position(l, 0) * psi(l);
        }

        // Multiply by the geometric factor
        W *= r;

        for (unsigned cosine_index = 0; cosine_index < 2; cosine_index++)
        {
          // compute  the velocity and the Lagrange multiplier
          Vector<double> interpolated_u(dim_el + 1, 0.0);
          double lambda = 0.0;

          // Loop over nodes
          for (unsigned j = 0; j < n_node; j++)
          {
            // get the value at which the velocities are stored
            Vector<unsigned> u_index(dim_el + 1);
            for (unsigned i = 0; i < dim_el + 1; i++)
            {
              u_index[i] = this->u_index_axi_nst(j, i);
            }

            // Assemble the velocity component
            for (unsigned i = 0; i < dim_el + 1; i++)
            {
              interpolated_u[i] += u(j, i, cosine_index) * psi(j);
            }

            // Cast to a boundary node
            BoundaryNodeBase* bnod_pt =
              dynamic_cast<BoundaryNodeBase*>(node_pt(j));

            // get the node
            Node* nod_pt = node_pt(j);

            // Get the index of the first nodal value associated with
            // this FaceElement
            unsigned first_index =
              bnod_pt->index_of_first_value_assigned_by_face_element(Id) +
              cosine_index;

            // Assemble the Lagrange multiplier
            lambda += nod_pt->value(first_index) * psi(j);
          }

          // compute the normal vector
          outer_unit_normal(ipt, norm_vec);

          // Assemble residuals and jacobian

          // Loop over the nodes
          for (unsigned j = 0; j < n_node; j++)
          {
            // Cast to a boundary node
            BoundaryNodeBase* bnod_pt =
              dynamic_cast<BoundaryNodeBase*>(node_pt(j));

            // Get the index of the first nodal value associated with
            // this FaceElement
            unsigned first_index =
              bnod_pt->index_of_first_value_assigned_by_face_element(Id) +
              cosine_index;

            // Local eqn number for the l-th component of lamdba
            // in the j-th element
            local_eqn = nodal_local_eqn(j, first_index);

            if (local_eqn >= 0)
            {
              for (unsigned i = 0; i < dim_el + 1; i++)
              {
                // Assemble residual for lagrange multiplier
                residuals[local_eqn] +=
                  interpolated_u[i] * norm_vec[i] * psi(j) * W;

                // Assemble Jacobian for Lagrange multiplier:
                if (flag == 1)
                {
                  // Loop over the nodes again for unknowns
                  for (unsigned jj = 0; jj < n_node; jj++)
                  {
                    // Local eqn number for the i-th component
                    // of the velocity in the jj-th element
                    local_unknown =
                      this->nodal_local_eqn(jj, 4 + 2 * i + cosine_index);
                    if (local_unknown >= 0)
                    {
                      jacobian(local_eqn, local_unknown) +=
                        norm_vec[i] * psi(jj) * psi(j) * W;
                    }
                  }
                }
              }
            }

            // Loop over the directions
            for (unsigned i = 0; i < dim_el + 1; i++)
            {
              // Local eqn number for the i-th component of the
              // velocity in the j-th element
              local_eqn = this->nodal_local_eqn(j, 4 + 2 * i + cosine_index);

              if (local_eqn >= 0)
              {
                // Add lagrange multiplier contribution to the bulk equation
                // Add to residual
                residuals[local_eqn] += norm_vec[i] * psi(j) * lambda * W;

                // Do Jacobian too?
                if (flag == 1)
                {
                  // Loop over the nodes again for unknowns
                  for (unsigned jj = 0; jj < n_node; jj++)
                  {
                    // Cast to a boundary node
                    BoundaryNodeBase* bnode_pt =
                      dynamic_cast<BoundaryNodeBase*>(node_pt(jj));

                    // Local eqn number for the l-th component of lamdba
                    // in the jj-th element
                    local_unknown = nodal_local_eqn(
                      jj,
                      bnode_pt->index_of_first_value_assigned_by_face_element(
                        Id) +
                        cosine_index);
                    if (local_unknown >= 0)
                    {
                      jacobian(local_eqn, local_unknown) +=
                        norm_vec[i] * psi(jj) * psi(j) * W;
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

    /// Calculate the Lagrange multipler at the local coordinate s.
    double interpolated_lambda(const Vector<double>& s, const unsigned& j)
    {
      // Find the number of nodes
      const unsigned n_node = this->nnode();
      // Find the number of positional types
      const unsigned n_position_type = this->nnodal_position_type();
      // Assign storage for the local shape function
      Shape psi(n_node, n_position_type);
      // Find the values of shape function
      this->shape(s, psi);

      // Initialise value of lambda
      double interpolated_lambda = 0.0;

      // Assemble the Lagrange multiplier
      // Loop over the local nodes
      for (unsigned l = 0; l < n_node; l++)
      {
        // Add contribution to pressure
        interpolated_lambda +=
          this->nodal_value(l, lagrange_multiplier_index(l, j)) * psi(l);
      }

      return (interpolated_lambda);
    }
  };
}; // namespace oomph
#endif
