name: macOS self-tests

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          brew install make automake libtool autoconf doxygen
          brew reinstall gfortran

      - name: Extra config
        run:
          printf '%s\n' '--enable-suppress-cgal-build --disable-shared' >> config/configure_options/default \
          && ( export LC_ALL=C; sort -o config/configure_options/default config/configure_options/default )

      - name: Build
        run: ./non_interactive_autogen.sh -s -j$(nproc)

      - name: Validate
        run: ./bin/parallel_self_test.py

      - name: Upload validation log file
        uses: actions/upload-artifact@v2
        with:
          name: macos-latest validation log
          path: ./validation.log
