name: Ubuntu self-tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install requirements
        run: sudo apt-get install make automake libtool libtool-bin autoconf doxygen gfortran g++

      - name: Build
        run: ./non_interactive_autogen.sh -s -j$(nproc)

      # Continue running even if the test fails so that the validation.log can be
      # uploaded and reviewed later on
      - name: Validate
        id: self_tests
        run: ./bin/parallel_self_test.py
        continue-on-error: true

      - name: Upload validation log file
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-latest validation log
          path: ./validation.log

      - name: Propagate self-test status
        if: steps.self_tests.outcome == 'failure'
        run: exit 1
