name: Ubuntu self-tests

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            install-script: sudo apt-get install make automake libtool libtool-bin autoconf doxygen gfortran g++

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: ${{ matrix.install-script }}
    - name: Extra config
      run: printf '%s\n' '${{ matrix.extra-config }}' >> config/configure_options/default \
           && ( export LC_ALL=C; sort -o config/configure_options/default config/configure_options/default )
    - name: Build
      run: ./non_interactive_autogen.sh -s
    - name: Validate
      run: make check -k -s
    - name: Upload validation log file
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }} validation log
        path: ./validation.log
